# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

FROM python:3.12-bullseye

WORKDIR /app

COPY inventory_artifacts.py /app/

CMD ["python3", "/app/inventory_artifacts.py"]
