# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

FROM scratch
COPY fixture /fixture
USER 1000:1000
ENTRYPOINT ["/fixture"]
