# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

image:
  repository: ""
  digest: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []

credentials:
  serviceToken: ""
  clientToken: ""
  workers: []

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi

podAnnotations: {}
