# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

stateMetrics:
  namespace: nvcf
  nameOverride: ""
  fullnameOverride: ""
  replicaCount: 1

  image:
    registry: "" # must be supplied
    repository: "" # must be supplied
    pullPolicy: IfNotPresent
    tag: "1.24.0"
  imagePullSecrets: []

  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext:
    capabilities:
      drop:
        - ALL
    runAsUser: 1000

  service:
    type: ClusterIP
    port: 9464
    targetPort: 9464
    portName: metrics
  terminationGracePeriodSeconds: 30

  resources:
    limits:
      cpu: "4"
      memory: 8Gi
    requests:
      cpu: "4"
      memory: 8Gi

  readinessProbe:
    httpGet:
      path: /favicon.ico
      port: metrics
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
    successThreshold: 1
    timeoutSeconds: 5
  livenessProbe:
    httpGet:
      path: /favicon.ico
      port: metrics
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

  volumes:
    - name: token
      projected:
        sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 3600
              audience: http://openbao-server.vault-system.svc.cluster.local:8200
  volumeMounts:
    - name: token
      mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      readOnly: true
  nodeSelector: {}
  tolerations: []
  affinity: {}

  ports:
    - name: metrics
      containerPort: 9464
      protocol: TCP

  env:
    NVCF_ENV: local
    NVCF_WORKERS: "10"
    NVCF_THANOS_NVCF: "false"
    NVCF_THANOS_NVCF_V1: "false"
    NVCF_THANOS_NVCFSRE: "false"
    NVCF_JWT_TOKEN_FILE: /vault/secrets/nvcf_jwt_token.txt
    NVCF_ENABLE_NGC_ENRICHMENT: "false"
    NVCF_API_URL: http://api.nvcf.svc.cluster.local:8080

  serviceMonitor:
    enabled: true
    interval: 50s
    scrapeTimeout: 45s
    path: /metrics
    labels: {}
