{{/*
SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
SPDX-License-Identifier: Apache-2.0

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-nvcf-invocation-service.name" . }}
  labels:
    {{ include "helm-nvcf-invocation-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm-nvcf-invocation-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm-nvcf-invocation-service.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.affinity }}
      affinity:
        {{- .Values.affinity | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      # Calculate network values for linking the app to the otel collector sidecar
      {{- $otelCollectorValues := include "otel-collector.values" . | fromYaml }}
      containers:
        {{- if .Values.otelCollector.enabled }}
        {{- include "otelCollector.sidecar" (dict "Values" $otelCollectorValues "Chart" .Chart) | nindent 8 }}
        {{- end }}
        - name: {{ include "helm-nvcf-invocation-service.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [{{ .Values.entrypoint.command }}]
          args:
            {{- if .Values.entrypoint.args }}
            {{- toYaml .Values.entrypoint.args | nindent 12 }}
            {{- end }}
            - "--config"
            - "{{ .Values.entrypoint.configPath }}"
          env:
            - name: OTEL_SERVICE_NAME
              value: {{ include "helm-nvcf-invocation-service.name" . }}
            {{- range $envName, $envValue := .Values.env }}
            - name: {{ $envName }}
              value: "{{ $envValue }}"
            {{- end }}
            {{- range $envName, $secret := .Values.envFromSecret }}
            - name: {{ $envName }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secret.name }}
                  key: {{ $secret.key }}
            {{- end }}
          livenessProbe:
            failureThreshold: 5
            grpc:
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.service.livenessProbe.delaySeconds }}
          readinessProbe:
            failureThreshold: 5
            grpc:
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.service.readinessProbe.delaySeconds }}
          startupProbe:
            failureThreshold: 5
            grpc:
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.service.startupProbe.delaySeconds }}
          ports:
            - name: grpc
              containerPort: {{  .Values.service.port }}
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: settings
              mountPath: {{ .Values.entrypoint.configPath }}
              subPath: {{ base .Values.entrypoint.configPath }}
              readOnly: true
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
      volumes:
        {{- if .Values.otelCollector.enabled }}
        {{- include "otelCollector.volumes" (dict "Values" $otelCollectorValues "Chart" .Chart) | nindent 8 }}
        {{- end }}
        - name: settings
          configMap:
            name: {{ include "helm-nvcf-invocation-service.name" . }}-settings-configmap
