# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

clusterIssuerName: compute-plane-ca-issuer

groveOperator:
  enabled: false
  namespace: grove-system
  certificateName: grove-webhook-cert
  secretName: grove-webhook-server-cert
  serviceName: grove-operator
