# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nvcf-state-metrics.fullname" . }}
  namespace: {{ include "nvcf-state-metrics.namespace" . }}
  labels:
    {{- include "nvcf-state-metrics.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.stateMetrics.replicaCount }}
  selector:
    matchLabels:
      {{- include "nvcf-state-metrics.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "nvcf-state-metrics.vaultAnnotations" . | nindent 8 }}
        {{- with .Values.stateMetrics.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.stateMetrics.env }}
        checksum/config-env: {{ toYaml .Values.stateMetrics.env | sha256sum }}
        {{- end }}
      labels:
        {{- include "nvcf-state-metrics.selectorLabels" . | nindent 8 }}
        {{- with .Values.stateMetrics.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.stateMetrics.terminationGracePeriodSeconds }}
      {{- with .Values.stateMetrics.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: nvcf-state-metrics
      securityContext:
        {{- toYaml .Values.stateMetrics.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.stateMetrics.securityContext | nindent 12 }}
          image: "{{ include "nvcf-state-metrics.image" . }}"
          imagePullPolicy: {{ .Values.stateMetrics.image.pullPolicy }}
          volumeMounts:
            {{- with .Values.stateMetrics.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: vault-config-templates
              mountPath: /vault/config/templates
              readOnly: true
          {{- with .Values.stateMetrics.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.stateMetrics.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.stateMetrics.env }}
          envFrom:
            - configMapRef:
                name: {{ include "nvcf-state-metrics.fullname" . }}-env
          {{- end }}
          ports:
            {{- toYaml .Values.stateMetrics.ports | nindent 12 }}
          resources:
            {{- toYaml .Values.stateMetrics.resources | nindent 12 }}
      volumes:
        {{- with .Values.stateMetrics.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: vault-config-templates
          configMap:
            name: {{ include "nvcf-state-metrics.fullname" . }}-vault-agent-tpl
            items:
              - key: nvcf_jwt_token.tmpl
                path: nvcf_jwt_token.tmpl
      {{- with .Values.stateMetrics.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stateMetrics.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stateMetrics.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
