# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
{{ if .Values.stateMetrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "nvcf-state-metrics.fullname" . }}
  namespace: {{ include "nvcf-state-metrics.namespace" . }}
  labels:
    {{- include "nvcf-state-metrics.labels" . | nindent 4 }}
    {{- with .Values.stateMetrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "nvcf-state-metrics.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.stateMetrics.service.portName }}
      path: {{ .Values.stateMetrics.serviceMonitor.path }}
      interval: {{ .Values.stateMetrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.stateMetrics.serviceMonitor.scrapeTimeout }}
{{ end }}
