/*
SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
SPDX-License-Identifier: Apache-2.0

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v2beta1

import (
	nvcav2beta1 "github.com/NVIDIA/nvcf/src/compute-plane-services/nvca/pkg/apis/nvca/v2beta1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ModelCacheBindingLister helps list ModelCacheBindings.
// All objects returned here must be treated as read-only.
type ModelCacheBindingLister interface {
	// List lists all ModelCacheBindings in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*nvcav2beta1.ModelCacheBinding, err error)
	// ModelCacheBindings returns an object that can list and get ModelCacheBindings.
	ModelCacheBindings(namespace string) ModelCacheBindingNamespaceLister
	ModelCacheBindingListerExpansion
}

// modelCacheBindingLister implements the ModelCacheBindingLister interface.
type modelCacheBindingLister struct {
	listers.ResourceIndexer[*nvcav2beta1.ModelCacheBinding]
}

// NewModelCacheBindingLister returns a new ModelCacheBindingLister.
func NewModelCacheBindingLister(indexer cache.Indexer) ModelCacheBindingLister {
	return &modelCacheBindingLister{listers.New[*nvcav2beta1.ModelCacheBinding](indexer, nvcav2beta1.Resource("modelcachebinding"))}
}

// ModelCacheBindings returns an object that can list and get ModelCacheBindings.
func (s *modelCacheBindingLister) ModelCacheBindings(namespace string) ModelCacheBindingNamespaceLister {
	return modelCacheBindingNamespaceLister{listers.NewNamespaced[*nvcav2beta1.ModelCacheBinding](s.ResourceIndexer, namespace)}
}

// ModelCacheBindingNamespaceLister helps list and get ModelCacheBindings.
// All objects returned here must be treated as read-only.
type ModelCacheBindingNamespaceLister interface {
	// List lists all ModelCacheBindings in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*nvcav2beta1.ModelCacheBinding, err error)
	// Get retrieves the ModelCacheBinding from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*nvcav2beta1.ModelCacheBinding, error)
	ModelCacheBindingNamespaceListerExpansion
}

// modelCacheBindingNamespaceLister implements the ModelCacheBindingNamespaceLister
// interface.
type modelCacheBindingNamespaceLister struct {
	listers.ResourceIndexer[*nvcav2beta1.ModelCacheBinding]
}
