load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "api_lib",
    srcs = ["main.go"],
    importpath = "github.com/NVIDIA/nvcf/src/control-plane-services/event-ledger/cmd/api",
    visibility = ["//visibility:private"],
    deps = [
        "//src/control-plane-services/event-ledger/cmd/api/startup",
        "//src/control-plane-services/event-ledger/internal/observability/logging",
        "//src/control-plane-services/event-ledger/pkg/constants",
    ],
)

go_binary(
    name = "api",
    embed = [":api_lib"],
    visibility = ["//visibility:public"],
)
