load("//rules/java:defs.bzl", "nv_boot_library", "nv_boot_library_test")
load("//rules/java:spring.bzl", "spring_boot_app")

package(default_visibility = ["//visibility:public"])

ESS_SERVICE_SRCS = glob(["src/main/java/**/*.java"])

ESS_SERVICE_RESOURCES = glob(["src/main/resources/**"])

ESS_SERVICE_TEST_SRCS = glob(["src/test/java/**/*.java"])

ESS_SERVICE_TEST_RESOURCES = glob(["src/test/resources/**"])

nv_boot_library(
    name = "app_classes",
    srcs = ESS_SERVICE_SRCS,
    deps = [
        "//src/control-plane-services/ess/ess-core:ess_core",
        "@nv_third_party_deps//:org_springframework_boot_spring_boot",
        "@nv_third_party_deps//:org_springframework_boot_spring_boot_autoconfigure",
        "@nv_third_party_deps//:org_springframework_data_spring_data_cassandra",
        "@nv_third_party_deps//:org_springframework_spring_context",
    ],
    javacopts = ["-parameters", "--release", "25"],
    resource_strip_prefix = "src/control-plane-services/ess/ess-service/src/main/resources",
    resources = ESS_SERVICE_RESOURCES,
    runtime_deps = [
        "@nv_third_party_deps//:org_springframework_boot_spring_boot_jarmode_tools",
    ],
    visibility = ["//visibility:private"],
)

spring_boot_app(
    name = "app",
    application = ":app_classes",
    artifact_id = "ess-service",
    artifact_name = "Encrypted Secret Store OSS",
    artifact_version = "0.0.1-SNAPSHOT",
    description = "NVIDIA Encrypted Secret Store OSS executable",
    group_id = "com.nvidia.ess",
    main_class = "com.nvidia.ess.EssServiceApplication",
)

nv_boot_library_test(
    name = "tests",
    coverage_library = ":app_classes",
    javacopts = ["-parameters", "--release", "25"],
    data = [
        "//src/control-plane-services/ess:secrets_json",
        "//src/control-plane-services/ess:test_local_env",
    ],
    resource_strip_prefix = "src/control-plane-services/ess/ess-service/src/test/resources",
    resources = ESS_SERVICE_TEST_RESOURCES,
    runtime_deps = [
        "//src/control-plane-services/ess:local_env_resources",
    ],
    size = "large",
    srcs = ESS_SERVICE_TEST_SRCS,
    tags = [
        "exclusive",
        "requires-docker",
    ],
    deps = [
        ":app_classes",
        "//src/control-plane-services/ess/ess-core:ess_core",
        "//src/control-plane-services/ess/ess-encryption:ess_encryption",
        "@nv_third_party_deps//:io_projectreactor_reactor_test",
        "@nv_third_party_deps//:org_slf4j_slf4j_api",
        "@nv_third_party_deps//:org_springframework_boot_spring_boot",
        "@nv_third_party_deps//:org_springframework_boot_spring_boot_actuator_autoconfigure",
        "@nv_third_party_deps//:org_springframework_boot_spring_boot_starter_test",
        "@nv_third_party_deps//:org_springframework_boot_spring_boot_testcontainers",
        "@nv_third_party_deps//:org_springframework_spring_beans",
        "@nv_third_party_deps//:org_springframework_spring_context",
        "@nv_third_party_deps//:org_springframework_spring_core",
        "@nv_third_party_deps//:org_springframework_spring_web",
        "@nv_third_party_deps//:org_testcontainers_testcontainers",
        "@nv_third_party_deps//:org_testcontainers_testcontainers_cassandra",
    ],
    timeout = "long",
)
