# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stargate-dev-mockdc.fullname" . }}-worker-credentials
  labels:
    {{- include "stargate-dev-mockdc.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ required "workerToken is required" .Values.workerToken | quote }}
