// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: nvct.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Worker_Connect_FullMethodName                  = "/nvct.Worker/Connect"
	Worker_SendHeartbeat_FullMethodName            = "/nvct.Worker/SendHeartbeat"
	Worker_SendResultMetadata_FullMethodName       = "/nvct.Worker/SendResultMetadata"
	Worker_GetArtifacts_FullMethodName             = "/nvct.Worker/GetArtifacts"
	Worker_RefreshToken_FullMethodName             = "/nvct.Worker/RefreshToken"
	Worker_RequestSecretCredentials_FullMethodName = "/nvct.Worker/RequestSecretCredentials"
)

// WorkerClient is the client API for Worker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkerClient interface {
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
	SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	SendResultMetadata(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ResultMetadataRequest, ResultMetadataResponse], error)
	GetArtifacts(ctx context.Context, in *ArtifactsRequest, opts ...grpc.CallOption) (*ArtifactsResponse, error)
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
	RequestSecretCredentials(ctx context.Context, in *SecretCredentialsRequest, opts ...grpc.CallOption) (*SecretCredentialsResponse, error)
}

type workerClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerClient(cc grpc.ClientConnInterface) WorkerClient {
	return &workerClient{cc}
}

func (c *workerClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, Worker_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, Worker_SendHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) SendResultMetadata(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ResultMetadataRequest, ResultMetadataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Worker_ServiceDesc.Streams[0], Worker_SendResultMetadata_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ResultMetadataRequest, ResultMetadataResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Worker_SendResultMetadataClient = grpc.ClientStreamingClient[ResultMetadataRequest, ResultMetadataResponse]

func (c *workerClient) GetArtifacts(ctx context.Context, in *ArtifactsRequest, opts ...grpc.CallOption) (*ArtifactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArtifactsResponse)
	err := c.cc.Invoke(ctx, Worker_GetArtifacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshTokenResponse)
	err := c.cc.Invoke(ctx, Worker_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) RequestSecretCredentials(ctx context.Context, in *SecretCredentialsRequest, opts ...grpc.CallOption) (*SecretCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecretCredentialsResponse)
	err := c.cc.Invoke(ctx, Worker_RequestSecretCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServer is the server API for Worker service.
// All implementations must embed UnimplementedWorkerServer
// for forward compatibility.
type WorkerServer interface {
	Connect(context.Context, *ConnectRequest) (*ConnectResponse, error)
	SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	SendResultMetadata(grpc.ClientStreamingServer[ResultMetadataRequest, ResultMetadataResponse]) error
	GetArtifacts(context.Context, *ArtifactsRequest) (*ArtifactsResponse, error)
	RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error)
	RequestSecretCredentials(context.Context, *SecretCredentialsRequest) (*SecretCredentialsResponse, error)
	mustEmbedUnimplementedWorkerServer()
}

// UnimplementedWorkerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerServer struct{}

func (UnimplementedWorkerServer) Connect(context.Context, *ConnectRequest) (*ConnectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedWorkerServer) SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedWorkerServer) SendResultMetadata(grpc.ClientStreamingServer[ResultMetadataRequest, ResultMetadataResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SendResultMetadata not implemented")
}
func (UnimplementedWorkerServer) GetArtifacts(context.Context, *ArtifactsRequest) (*ArtifactsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArtifacts not implemented")
}
func (UnimplementedWorkerServer) RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedWorkerServer) RequestSecretCredentials(context.Context, *SecretCredentialsRequest) (*SecretCredentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestSecretCredentials not implemented")
}
func (UnimplementedWorkerServer) mustEmbedUnimplementedWorkerServer() {}
func (UnimplementedWorkerServer) testEmbeddedByValue()                {}

// UnsafeWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServer will
// result in compilation errors.
type UnsafeWorkerServer interface {
	mustEmbedUnimplementedWorkerServer()
}

func RegisterWorkerServer(s grpc.ServiceRegistrar, srv WorkerServer) {
	// If the following call pancis, it indicates UnimplementedWorkerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Worker_ServiceDesc, srv)
}

func _Worker_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_SendHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).SendHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_SendHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).SendHeartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_SendResultMetadata_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkerServer).SendResultMetadata(&grpc.GenericServerStream[ResultMetadataRequest, ResultMetadataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Worker_SendResultMetadataServer = grpc.ClientStreamingServer[ResultMetadataRequest, ResultMetadataResponse]

func _Worker_GetArtifacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArtifactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).GetArtifacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_GetArtifacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).GetArtifacts(ctx, req.(*ArtifactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_RequestSecretCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecretCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).RequestSecretCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_RequestSecretCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).RequestSecretCredentials(ctx, req.(*SecretCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Worker_ServiceDesc is the grpc.ServiceDesc for Worker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Worker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nvct.Worker",
	HandlerType: (*WorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _Worker_Connect_Handler,
		},
		{
			MethodName: "SendHeartbeat",
			Handler:    _Worker_SendHeartbeat_Handler,
		},
		{
			MethodName: "GetArtifacts",
			Handler:    _Worker_GetArtifacts_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _Worker_RefreshToken_Handler,
		},
		{
			MethodName: "RequestSecretCredentials",
			Handler:    _Worker_RequestSecretCredentials_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendResultMetadata",
			Handler:       _Worker_SendResultMetadata_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "nvct.proto",
}

const (
	Skyway_AuthGetLogs_FullMethodName        = "/nvct.Skyway/AuthGetLogs"
	Skyway_AuthExecuteCommand_FullMethodName = "/nvct.Skyway/AuthExecuteCommand"
	Skyway_AuthListInstances_FullMethodName  = "/nvct.Skyway/AuthListInstances"
)

// SkywayClient is the client API for Skyway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SkywayClient interface {
	AuthGetLogs(ctx context.Context, in *SkywayAuthRequest, opts ...grpc.CallOption) (*SkywayAuthResponse, error)
	AuthExecuteCommand(ctx context.Context, in *SkywayAuthRequest, opts ...grpc.CallOption) (*SkywayAuthResponse, error)
	AuthListInstances(ctx context.Context, in *SkywayAuthRequest, opts ...grpc.CallOption) (*SkywayAuthResponse, error)
}

type skywayClient struct {
	cc grpc.ClientConnInterface
}

func NewSkywayClient(cc grpc.ClientConnInterface) SkywayClient {
	return &skywayClient{cc}
}

func (c *skywayClient) AuthGetLogs(ctx context.Context, in *SkywayAuthRequest, opts ...grpc.CallOption) (*SkywayAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkywayAuthResponse)
	err := c.cc.Invoke(ctx, Skyway_AuthGetLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skywayClient) AuthExecuteCommand(ctx context.Context, in *SkywayAuthRequest, opts ...grpc.CallOption) (*SkywayAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkywayAuthResponse)
	err := c.cc.Invoke(ctx, Skyway_AuthExecuteCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skywayClient) AuthListInstances(ctx context.Context, in *SkywayAuthRequest, opts ...grpc.CallOption) (*SkywayAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkywayAuthResponse)
	err := c.cc.Invoke(ctx, Skyway_AuthListInstances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SkywayServer is the server API for Skyway service.
// All implementations must embed UnimplementedSkywayServer
// for forward compatibility.
type SkywayServer interface {
	AuthGetLogs(context.Context, *SkywayAuthRequest) (*SkywayAuthResponse, error)
	AuthExecuteCommand(context.Context, *SkywayAuthRequest) (*SkywayAuthResponse, error)
	AuthListInstances(context.Context, *SkywayAuthRequest) (*SkywayAuthResponse, error)
	mustEmbedUnimplementedSkywayServer()
}

// UnimplementedSkywayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSkywayServer struct{}

func (UnimplementedSkywayServer) AuthGetLogs(context.Context, *SkywayAuthRequest) (*SkywayAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthGetLogs not implemented")
}
func (UnimplementedSkywayServer) AuthExecuteCommand(context.Context, *SkywayAuthRequest) (*SkywayAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthExecuteCommand not implemented")
}
func (UnimplementedSkywayServer) AuthListInstances(context.Context, *SkywayAuthRequest) (*SkywayAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthListInstances not implemented")
}
func (UnimplementedSkywayServer) mustEmbedUnimplementedSkywayServer() {}
func (UnimplementedSkywayServer) testEmbeddedByValue()                {}

// UnsafeSkywayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SkywayServer will
// result in compilation errors.
type UnsafeSkywayServer interface {
	mustEmbedUnimplementedSkywayServer()
}

func RegisterSkywayServer(s grpc.ServiceRegistrar, srv SkywayServer) {
	// If the following call pancis, it indicates UnimplementedSkywayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Skyway_ServiceDesc, srv)
}

func _Skyway_AuthGetLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkywayAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkywayServer).AuthGetLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Skyway_AuthGetLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkywayServer).AuthGetLogs(ctx, req.(*SkywayAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Skyway_AuthExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkywayAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkywayServer).AuthExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Skyway_AuthExecuteCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkywayServer).AuthExecuteCommand(ctx, req.(*SkywayAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Skyway_AuthListInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkywayAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkywayServer).AuthListInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Skyway_AuthListInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkywayServer).AuthListInstances(ctx, req.(*SkywayAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Skyway_ServiceDesc is the grpc.ServiceDesc for Skyway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Skyway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nvct.Skyway",
	HandlerType: (*SkywayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthGetLogs",
			Handler:    _Skyway_AuthGetLogs_Handler,
		},
		{
			MethodName: "AuthExecuteCommand",
			Handler:    _Skyway_AuthExecuteCommand_Handler,
		},
		{
			MethodName: "AuthListInstances",
			Handler:    _Skyway_AuthListInstances_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nvct.proto",
}
