// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: nvct.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutionStatus int32

const (
	ExecutionStatus_ERRORED                       ExecutionStatus = 0
	ExecutionStatus_IN_PROGRESS                   ExecutionStatus = 1
	ExecutionStatus_COMPLETED                     ExecutionStatus = 2
	ExecutionStatus_PENDING_EVALUATION            ExecutionStatus = 3
	ExecutionStatus_EXCEEDED_MAX_RUNTIME_DURATION ExecutionStatus = 4
	ExecutionStatus_EXCEEDED_MAX_QUEUED_DURATION  ExecutionStatus = 5
	ExecutionStatus_QUEUED                        ExecutionStatus = 6
	ExecutionStatus_LAUNCHED                      ExecutionStatus = 7
	ExecutionStatus_RUNNING                       ExecutionStatus = 8
	ExecutionStatus_CANCELED                      ExecutionStatus = 9
	ExecutionStatus_TASK_CONTAINER_INITIALIZING   ExecutionStatus = 10
	ExecutionStatus_WORKER_TERMINATED             ExecutionStatus = 11
)

// Enum value maps for ExecutionStatus.
var (
	ExecutionStatus_name = map[int32]string{
		0:  "ERRORED",
		1:  "IN_PROGRESS",
		2:  "COMPLETED",
		3:  "PENDING_EVALUATION",
		4:  "EXCEEDED_MAX_RUNTIME_DURATION",
		5:  "EXCEEDED_MAX_QUEUED_DURATION",
		6:  "QUEUED",
		7:  "LAUNCHED",
		8:  "RUNNING",
		9:  "CANCELED",
		10: "TASK_CONTAINER_INITIALIZING",
		11: "WORKER_TERMINATED",
	}
	ExecutionStatus_value = map[string]int32{
		"ERRORED":                       0,
		"IN_PROGRESS":                   1,
		"COMPLETED":                     2,
		"PENDING_EVALUATION":            3,
		"EXCEEDED_MAX_RUNTIME_DURATION": 4,
		"EXCEEDED_MAX_QUEUED_DURATION":  5,
		"QUEUED":                        6,
		"LAUNCHED":                      7,
		"RUNNING":                       8,
		"CANCELED":                      9,
		"TASK_CONTAINER_INITIALIZING":   10,
		"WORKER_TERMINATED":             11,
	}
)

func (x ExecutionStatus) Enum() *ExecutionStatus {
	p := new(ExecutionStatus)
	*p = x
	return p
}

func (x ExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_nvct_proto_enumTypes[0].Descriptor()
}

func (ExecutionStatus) Type() protoreflect.EnumType {
	return &file_nvct_proto_enumTypes[0]
}

func (x ExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionStatus.Descriptor instead.
func (ExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_nvct_proto_rawDescGZIP(), []int{0}
}

type ArtifactsResponse_ArtifactResponse_ArtifactKindEnum int32

const (
	ArtifactsResponse_ArtifactResponse_MODEL    ArtifactsResponse_ArtifactResponse_ArtifactKindEnum = 0
	ArtifactsResponse_ArtifactResponse_RESOURCE ArtifactsResponse_ArtifactResponse_ArtifactKindEnum = 1
)

// Enum value maps for ArtifactsResponse_ArtifactResponse_ArtifactKindEnum.
var (
	ArtifactsResponse_ArtifactResponse_ArtifactKindEnum_name = map[int32]string{
		0: "MODEL",
		1: "RESOURCE",
	}
	ArtifactsResponse_ArtifactResponse_ArtifactKindEnum_value = map[string]int32{
		"MODEL":    0,
		"RESOURCE": 1,
	}
)

func (x ArtifactsResponse_ArtifactResponse_ArtifactKindEnum) Enum() *ArtifactsResponse_ArtifactResponse_ArtifactKindEnum {
	p := new(ArtifactsResponse_ArtifactResponse_ArtifactKindEnum)
	*p = x
	return p
}

func (x ArtifactsResponse_ArtifactResponse_ArtifactKindEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArtifactsResponse_ArtifactResponse_ArtifactKindEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_nvct_proto_enumTypes[1].Descriptor()
}

func (ArtifactsResponse_ArtifactResponse_ArtifactKindEnum) Type() protoreflect.EnumType {
	return &file_nvct_proto_enumTypes[1]
}

func (x ArtifactsResponse_ArtifactResponse_ArtifactKindEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArtifactsResponse_ArtifactResponse_ArtifactKindEnum.Descriptor instead.
func (ArtifactsResponse_ArtifactResponse_ArtifactKindEnum) EnumDescriptor() ([]byte, []int) {
	return file_nvct_proto_rawDescGZIP(), []int{10, 0, 0}
}

type ConnectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstanceId string `protobuf:"bytes,1,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	TaskId     string `protobuf:"bytes,2,opt,name=taskId,proto3" json:"taskId,omitempty"`
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nvct_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nvct_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_nvct_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ConnectRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type ConnectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConnectedRegion string `protobuf:"bytes,1,opt,name=connectedRegion,proto3" json:"connectedRegion,omitempty"`
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nvct_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nvct_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_nvct_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectResponse) GetConnectedRegion() string {
	if x != nil {
		return x.ConnectedRegion
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstanceId   string          `protobuf:"bytes,1,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	TaskId       string          `protobuf:"bytes,2,opt,name=taskId,proto3" json:"taskId,omitempty"`
	InstanceType string          `protobuf:"bytes,3,opt,name=instanceType,proto3" json:"instanceType,omitempty"`
	Status       ExecutionStatus `protobuf:"varint,4,opt,name=status,proto3,enum=nvct.ExecutionStatus" json:"status,omitempty"` // ERRORED, EXCEEDED_MAX_DURATION
	ErrorMessage *string         `protobuf:"bytes,5,opt,name=errorMessage,proto3,oneof" json:"errorMessage,omitempty"`
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nvct_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nvct_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_nvct_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *HeartbeatRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *HeartbeatRequest) GetInstanceType() string {
	if x != nil {
		return x.InstanceType
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_ERRORED
}

func (x *HeartbeatRequest) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId          string `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`                   // UUID
	ExecutionStatus string `protobuf:"bytes,2,opt,name=ExecutionStatus,proto3" json:"ExecutionStatus,omitempty"` // COMPLETED, ERRORED, etc.
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nvct_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nvct_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_nvct_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *HeartbeatResponse) GetExecutionStatus() string {
	if x != nil {
		return x.ExecutionStatus
	}
	return ""
}

type StringKV struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *StringKV) Reset() {
	*x = StringKV{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nvct_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringKV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringKV) ProtoMessage() {}

func (x *StringKV) ProtoReflect() protoreflect.Message {
	mi := &file_nvct_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringKV.ProtoReflect.Descriptor instead.
func (*StringKV) Descriptor() ([]byte, []int) {
	return file_nvct_proto_rawDescGZIP(), []int{4}
}

func (x *StringKV) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StringKV) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ResultMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body []byte `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *ResultMetadata) Reset() {
	*x = ResultMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nvct_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultMetadata) ProtoMessage() {}

func (x *ResultMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_nvct_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultMetadata.ProtoReflect.Descriptor instead.
func (*ResultMetadata) Descriptor() ([]byte, []int) {
	return file_nvct_proto_rawDescGZIP(), []int{5}
}

func (x *ResultMetadata) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type ErrorDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Title  string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Status uint32 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Detail string `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
}

func (x *ErrorDetails) Reset() {
	*x = ErrorDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nvct_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetails) ProtoMessage() {}

func (x *ErrorDetails) ProtoReflect() protoreflect.Message {
	mi := &file_nvct_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetails.ProtoReflect.Descriptor instead.
func (*ErrorDetails) Descriptor() ([]byte, []int) {
	return file_nvct_proto_rawDescGZIP(), []int{6}
}

func (x *ErrorDetails) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ErrorDetails) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ErrorDetails) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ErrorDetails) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type ResultMetadataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId          string          `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`         // UUID
	InstanceId      string          `protobuf:"bytes,2,opt,name=instanceId,proto3" json:"instanceId,omitempty"` // UUID
	InstanceType    string          `protobuf:"bytes,3,opt,name=instanceType,proto3" json:"instanceType,omitempty"`
	Status          ExecutionStatus `protobuf:"varint,4,opt,name=status,proto3,enum=nvct.ExecutionStatus" json:"status,omitempty"` // ERRORED, IN_PROGRESS, COMPLETED, etc.
	PercentComplete *uint32         `protobuf:"varint,5,opt,name=percentComplete,proto3,oneof" json:"percentComplete,omitempty"`
	ResultName      string          `protobuf:"bytes,6,opt,name=resultName,proto3" json:"resultName,omitempty"` // Result/Checkpoints metadata
	// Types that are assignable to Result:
	//
	//	*ResultMetadataRequest_Metadata
	//	*ResultMetadataRequest_ErrorDetails
	Result isResultMetadataRequest_Result `protobuf_oneof:"result"`
}

func (x *ResultMetadataRequest) Reset() {
	*x = ResultMetadataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nvct_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultMetadataRequest) ProtoMessage() {}

func (x *ResultMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nvct_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultMetadataRequest.ProtoReflect.Descriptor instead.
func (*ResultMetadataRequest) Descriptor() ([]byte, []int) {
	return file_nvct_proto_rawDescGZIP(), []int{7}
}

func (x *ResultMetadataRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ResultMetadataRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ResultMetadataRequest) GetInstanceType() string {
	if x != nil {
		return x.InstanceType
	}
	return ""
}

func (x *ResultMetadataRequest) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_ERRORED
}

func (x *ResultMetadataRequest) GetPercentComplete() uint32 {
	if x != nil && x.PercentComplete != nil {
		return *x.PercentComplete
	}
	return 0
}

func (x *ResultMetadataRequest) GetResultName() string {
	if x != nil {
		return x.ResultName
	}
	return ""
}

func (m *ResultMetadataRequest) GetResult() isResultMetadataRequest_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *ResultMetadataRequest) GetMetadata() *ResultMetadata {
	if x, ok := x.GetResult().(*ResultMetadataRequest_Metadata); ok {
		return x.Metadata
	}
	return nil
}

func (x *ResultMetadataRequest) GetErrorDetails() *ErrorDetails {
	if x, ok := x.GetResult().(*ResultMetadataRequest_ErrorDetails); ok {
		return x.ErrorDetails
	}
	return nil
}

type isResultMetadataRequest_Result interface {
	isResultMetadataRequest_Result()
}

type ResultMetadataRequest_Metadata struct {
	Metadata *ResultMetadata `protobuf:"bytes,7,opt,name=metadata,proto3,oneof"` // Results/Checkpoints metadata
}

type ResultMetadataRequest_ErrorDetails struct {
	ErrorDetails *ErrorDetails `protobuf:"bytes,8,opt,name=errorDetails,proto3,oneof"`
}

func (*ResultMetadataRequest_Metadata) isResultMetadataRequest_Result() {}

func (*ResultMetadataRequest_ErrorDetails) isResultMetadataRequest_Result() {}

type ResultMetadataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId          string `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`                   // UUID
	ExecutionStatus string `protobuf:"bytes,2,opt,name=ExecutionStatus,proto3" json:"ExecutionStatus,omitempty"` // COMPLETED, ERRORED, etc.
}

func (x *ResultMetadataResponse) Reset() {
	*x = ResultMetadataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nvct_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultMetadataResponse) ProtoMessage() {}

func (x *ResultMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nvct_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultMetadataResponse.ProtoReflect.Descriptor instead.
func (*ResultMetadataResponse) Descriptor() ([]byte, []int) {
	return file_nvct_proto_rawDescGZIP(), []int{8}
}

func (x *ResultMetadataResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ResultMetadataResponse) GetExecutionStatus() string {
	if x != nil {
		return x.ExecutionStatus
	}
	return ""
}

type ArtifactsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId string `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"` // UUID
}

func (x *ArtifactsRequest) Reset() {
	*x = ArtifactsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nvct_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArtifactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactsRequest) ProtoMessage() {}

func (x *ArtifactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nvct_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactsRequest.ProtoReflect.Descriptor instead.
func (*ArtifactsRequest) Descriptor() ([]byte, []int) {
	return file_nvct_proto_rawDescGZIP(), []int{9}
}

func (x *ArtifactsRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type ArtifactsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Artifacts []*ArtifactsResponse_ArtifactResponse `protobuf:"bytes,1,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
}

func (x *ArtifactsResponse) Reset() {
	*x = ArtifactsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nvct_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArtifactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactsResponse) ProtoMessage() {}

func (x *ArtifactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nvct_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactsResponse.ProtoReflect.Descriptor instead.
func (*ArtifactsResponse) Descriptor() ([]byte, []int) {
	return file_nvct_proto_rawDescGZIP(), []int{10}
}

func (x *ArtifactsResponse) GetArtifacts() []*ArtifactsResponse_ArtifactResponse {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId string `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"` // UUID
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nvct_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nvct_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_nvct_proto_rawDescGZIP(), []int{11}
}

func (x *RefreshTokenRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nvct_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nvct_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_nvct_proto_rawDescGZIP(), []int{12}
}

func (x *RefreshTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type SecretCredentialsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId string `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
}

func (x *SecretCredentialsRequest) Reset() {
	*x = SecretCredentialsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nvct_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecretCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretCredentialsRequest) ProtoMessage() {}

func (x *SecretCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nvct_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretCredentialsRequest.ProtoReflect.Descriptor instead.
func (*SecretCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_nvct_proto_rawDescGZIP(), []int{13}
}

func (x *SecretCredentialsRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type SecretCredentialsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SecretCredentialsToken string                 `protobuf:"bytes,1,opt,name=secretCredentialsToken,proto3" json:"secretCredentialsToken,omitempty"`
	Expiration             *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expiration,proto3" json:"expiration,omitempty"`
}

func (x *SecretCredentialsResponse) Reset() {
	*x = SecretCredentialsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nvct_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecretCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretCredentialsResponse) ProtoMessage() {}

func (x *SecretCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nvct_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretCredentialsResponse.ProtoReflect.Descriptor instead.
func (*SecretCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_nvct_proto_rawDescGZIP(), []int{14}
}

func (x *SecretCredentialsResponse) GetSecretCredentialsToken() string {
	if x != nil {
		return x.SecretCredentialsToken
	}
	return ""
}

func (x *SecretCredentialsResponse) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

type SkywayAuthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientAuthorizationToken string `protobuf:"bytes,1,opt,name=clientAuthorizationToken,proto3" json:"clientAuthorizationToken,omitempty"`
	TaskId                   string `protobuf:"bytes,2,opt,name=taskId,proto3" json:"taskId,omitempty"`
	// used for super admins (KAS) to invoke on behalf of a given nca id
	TargetNcaId *string `protobuf:"bytes,3,opt,name=targetNcaId,proto3,oneof" json:"targetNcaId,omitempty"`
}

func (x *SkywayAuthRequest) Reset() {
	*x = SkywayAuthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nvct_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkywayAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkywayAuthRequest) ProtoMessage() {}

func (x *SkywayAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nvct_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkywayAuthRequest.ProtoReflect.Descriptor instead.
func (*SkywayAuthRequest) Descriptor() ([]byte, []int) {
	return file_nvct_proto_rawDescGZIP(), []int{15}
}

func (x *SkywayAuthRequest) GetClientAuthorizationToken() string {
	if x != nil {
		return x.ClientAuthorizationToken
	}
	return ""
}

func (x *SkywayAuthRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SkywayAuthRequest) GetTargetNcaId() string {
	if x != nil && x.TargetNcaId != nil {
		return *x.TargetNcaId
	}
	return ""
}

type SkywayAuthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId            string                         `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	ClientAuthSubject string                         `protobuf:"bytes,2,opt,name=clientAuthSubject,proto3" json:"clientAuthSubject,omitempty"`
	ClientNcaId       string                         `protobuf:"bytes,3,opt,name=clientNcaId,proto3" json:"clientNcaId,omitempty"`
	Backend           *string                        `protobuf:"bytes,4,opt,name=backend,proto3,oneof" json:"backend,omitempty"`
	Instances         []*SkywayAuthResponse_Instance `protobuf:"bytes,5,rep,name=instances,proto3" json:"instances,omitempty"`
}

func (x *SkywayAuthResponse) Reset() {
	*x = SkywayAuthResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nvct_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkywayAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkywayAuthResponse) ProtoMessage() {}

func (x *SkywayAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nvct_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkywayAuthResponse.ProtoReflect.Descriptor instead.
func (*SkywayAuthResponse) Descriptor() ([]byte, []int) {
	return file_nvct_proto_rawDescGZIP(), []int{16}
}

func (x *SkywayAuthResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SkywayAuthResponse) GetClientAuthSubject() string {
	if x != nil {
		return x.ClientAuthSubject
	}
	return ""
}

func (x *SkywayAuthResponse) GetClientNcaId() string {
	if x != nil {
		return x.ClientNcaId
	}
	return ""
}

func (x *SkywayAuthResponse) GetBackend() string {
	if x != nil && x.Backend != nil {
		return *x.Backend
	}
	return ""
}

func (x *SkywayAuthResponse) GetInstances() []*SkywayAuthResponse_Instance {
	if x != nil {
		return x.Instances
	}
	return nil
}

type ArtifactsResponse_ArtifactResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string                                              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string                                              `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Kind    ArtifactsResponse_ArtifactResponse_ArtifactKindEnum `protobuf:"varint,3,opt,name=kind,proto3,enum=nvct.ArtifactsResponse_ArtifactResponse_ArtifactKindEnum" json:"kind,omitempty"`
	Files   []*ArtifactsResponse_ArtifactResponse_ArtifactFile  `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
}

func (x *ArtifactsResponse_ArtifactResponse) Reset() {
	*x = ArtifactsResponse_ArtifactResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nvct_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArtifactsResponse_ArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactsResponse_ArtifactResponse) ProtoMessage() {}

func (x *ArtifactsResponse_ArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nvct_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactsResponse_ArtifactResponse.ProtoReflect.Descriptor instead.
func (*ArtifactsResponse_ArtifactResponse) Descriptor() ([]byte, []int) {
	return file_nvct_proto_rawDescGZIP(), []int{10, 0}
}

func (x *ArtifactsResponse_ArtifactResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArtifactsResponse_ArtifactResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ArtifactsResponse_ArtifactResponse) GetKind() ArtifactsResponse_ArtifactResponse_ArtifactKindEnum {
	if x != nil {
		return x.Kind
	}
	return ArtifactsResponse_ArtifactResponse_MODEL
}

func (x *ArtifactsResponse_ArtifactResponse) GetFiles() []*ArtifactsResponse_ArtifactResponse_ArtifactFile {
	if x != nil {
		return x.Files
	}
	return nil
}

type ArtifactsResponse_ArtifactResponse_ArtifactFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Url  string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *ArtifactsResponse_ArtifactResponse_ArtifactFile) Reset() {
	*x = ArtifactsResponse_ArtifactResponse_ArtifactFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nvct_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArtifactsResponse_ArtifactResponse_ArtifactFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactsResponse_ArtifactResponse_ArtifactFile) ProtoMessage() {}

func (x *ArtifactsResponse_ArtifactResponse_ArtifactFile) ProtoReflect() protoreflect.Message {
	mi := &file_nvct_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactsResponse_ArtifactResponse_ArtifactFile.ProtoReflect.Descriptor instead.
func (*ArtifactsResponse_ArtifactResponse_ArtifactFile) Descriptor() ([]byte, []int) {
	return file_nvct_proto_rawDescGZIP(), []int{10, 0, 0}
}

func (x *ArtifactsResponse_ArtifactResponse_ArtifactFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ArtifactsResponse_ArtifactResponse_ArtifactFile) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SkywayAuthResponse_Instance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstanceId string `protobuf:"bytes,1,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	Location   string `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	State      string `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *SkywayAuthResponse_Instance) Reset() {
	*x = SkywayAuthResponse_Instance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nvct_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkywayAuthResponse_Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkywayAuthResponse_Instance) ProtoMessage() {}

func (x *SkywayAuthResponse_Instance) ProtoReflect() protoreflect.Message {
	mi := &file_nvct_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkywayAuthResponse_Instance.ProtoReflect.Descriptor instead.
func (*SkywayAuthResponse_Instance) Descriptor() ([]byte, []int) {
	return file_nvct_proto_rawDescGZIP(), []int{16, 0}
}

func (x *SkywayAuthResponse_Instance) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *SkywayAuthResponse_Instance) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *SkywayAuthResponse_Instance) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

var File_nvct_proto protoreflect.FileDescriptor

var file_nvct_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6e, 0x76, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6e, 0x76,
	0x63, 0x74, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x48, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x22, 0x3b, 0x0a,
	0x0f, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x28, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x52, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x65, 0x64, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x22, 0xd7, 0x01, 0x0a, 0x10, 0x48,
	0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x6e, 0x76,
	0x63, 0x74, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x27, 0x0a, 0x0c, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x88, 0x01, 0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x55, 0x0a, 0x11, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73,
	0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49,
	0x64, 0x12, 0x28, 0x0a, 0x0f, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x32, 0x0a, 0x08, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x4b, 0x56, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x24, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x68, 0x0a, 0x0c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22,
	0xfd, 0x02, 0x0a, 0x15, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73,
	0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49,
	0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49,
	0x64, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x6e, 0x76, 0x63, 0x74, 0x2e, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x2d, 0x0a, 0x0f, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x43,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x01, 0x52,
	0x0f, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x88, 0x01, 0x01, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x32, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6e, 0x76, 0x63, 0x74, 0x2e, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x08, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x38, 0x0a, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x6e, 0x76, 0x63, 0x74, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x48, 0x00, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x12, 0x0a, 0x10, 0x5f,
	0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x22,
	0x5a, 0x0a, 0x16, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73,
	0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49,
	0x64, 0x12, 0x28, 0x0a, 0x0f, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2a, 0x0a, 0x10, 0x41,
	0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x22, 0x9d, 0x03, 0x0a, 0x11, 0x41, 0x72, 0x74, 0x69,
	0x66, 0x61, 0x63, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a,
	0x09, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x28, 0x2e, 0x6e, 0x76, 0x63, 0x74, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61,
	0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x09, 0x61, 0x72, 0x74, 0x69,
	0x66, 0x61, 0x63, 0x74, 0x73, 0x1a, 0xbf, 0x02, 0x0a, 0x10, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61,
	0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x4d, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x39, 0x2e, 0x6e, 0x76, 0x63, 0x74, 0x2e, 0x41, 0x72,
	0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x45, 0x6e, 0x75,
	0x6d, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x4b, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x6e, 0x76, 0x63, 0x74, 0x2e, 0x41, 0x72,
	0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x05, 0x66,
	0x69, 0x6c, 0x65, 0x73, 0x1a, 0x34, 0x0a, 0x0c, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74,
	0x46, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x2b, 0x0a, 0x10, 0x41, 0x72,
	0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x09,
	0x0a, 0x05, 0x4d, 0x4f, 0x44, 0x45, 0x4c, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x53,
	0x4f, 0x55, 0x52, 0x43, 0x45, 0x10, 0x01, 0x22, 0x2d, 0x0a, 0x13, 0x52, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x14, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73,
	0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x32, 0x0a, 0x18, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x22, 0x8f, 0x01, 0x0a, 0x19, 0x53, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x16, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x3a,
	0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x9e, 0x01, 0x0a, 0x11, 0x53,
	0x6b, 0x79, 0x77, 0x61, 0x79, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x3a, 0x0a, 0x18, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x18, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06,
	0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61,
	0x73, 0x6b, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4e, 0x63,
	0x61, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x4e, 0x63, 0x61, 0x49, 0x64, 0x88, 0x01, 0x01, 0x42, 0x0e, 0x0a, 0x0c, 0x5f,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4e, 0x63, 0x61, 0x49, 0x64, 0x22, 0xc6, 0x02, 0x0a, 0x12,
	0x53, 0x6b, 0x79, 0x77, 0x61, 0x79, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x11, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x41, 0x75, 0x74, 0x68, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x75, 0x74,
	0x68, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x4e, 0x63, 0x61, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4e, 0x63, 0x61, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x07, 0x62, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x62,
	0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x88, 0x01, 0x01, 0x12, 0x3f, 0x0a, 0x09, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6e,
	0x76, 0x63, 0x74, 0x2e, 0x53, 0x6b, 0x79, 0x77, 0x61, 0x79, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52,
	0x09, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x1a, 0x5c, 0x0a, 0x08, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x62, 0x61, 0x63,
	0x6b, 0x65, 0x6e, 0x64, 0x2a, 0x88, 0x02, 0x0a, 0x0f, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x4e, 0x5f, 0x50, 0x52, 0x4f, 0x47,
	0x52, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45,
	0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47,
	0x5f, 0x45, 0x56, 0x41, 0x4c, 0x55, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x03, 0x12, 0x21, 0x0a,
	0x1d, 0x45, 0x58, 0x43, 0x45, 0x45, 0x44, 0x45, 0x44, 0x5f, 0x4d, 0x41, 0x58, 0x5f, 0x52, 0x55,
	0x4e, 0x54, 0x49, 0x4d, 0x45, 0x5f, 0x44, 0x55, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x04,
	0x12, 0x20, 0x0a, 0x1c, 0x45, 0x58, 0x43, 0x45, 0x45, 0x44, 0x45, 0x44, 0x5f, 0x4d, 0x41, 0x58,
	0x5f, 0x51, 0x55, 0x45, 0x55, 0x45, 0x44, 0x5f, 0x44, 0x55, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e,
	0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06, 0x51, 0x55, 0x45, 0x55, 0x45, 0x44, 0x10, 0x06, 0x12, 0x0c,
	0x0a, 0x08, 0x4c, 0x41, 0x55, 0x4e, 0x43, 0x48, 0x45, 0x44, 0x10, 0x07, 0x12, 0x0b, 0x0a, 0x07,
	0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x08, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x41, 0x4e,
	0x43, 0x45, 0x4c, 0x45, 0x44, 0x10, 0x09, 0x12, 0x1f, 0x0a, 0x1b, 0x54, 0x41, 0x53, 0x4b, 0x5f,
	0x43, 0x4f, 0x4e, 0x54, 0x41, 0x49, 0x4e, 0x45, 0x52, 0x5f, 0x49, 0x4e, 0x49, 0x54, 0x49, 0x41,
	0x4c, 0x49, 0x5a, 0x49, 0x4e, 0x47, 0x10, 0x0a, 0x12, 0x15, 0x0a, 0x11, 0x57, 0x4f, 0x52, 0x4b,
	0x45, 0x52, 0x5f, 0x54, 0x45, 0x52, 0x4d, 0x49, 0x4e, 0x41, 0x54, 0x45, 0x44, 0x10, 0x0b, 0x32,
	0xba, 0x03, 0x0a, 0x06, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x12, 0x36, 0x0a, 0x07, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x14, 0x2e, 0x6e, 0x76, 0x63, 0x74, 0x2e, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6e, 0x76,
	0x63, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x40, 0x0a, 0x0d, 0x53, 0x65, 0x6e, 0x64, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62,
	0x65, 0x61, 0x74, 0x12, 0x16, 0x2e, 0x6e, 0x76, 0x63, 0x74, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6e, 0x76,
	0x63, 0x74, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x12, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x2e, 0x6e, 0x76, 0x63,
	0x74, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6e, 0x76, 0x63, 0x74, 0x2e, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x12, 0x3f, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x41, 0x72,
	0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x12, 0x16, 0x2e, 0x6e, 0x76, 0x63, 0x74, 0x2e, 0x41,
	0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x17, 0x2e, 0x6e, 0x76, 0x63, 0x74, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x0c, 0x52, 0x65, 0x66, 0x72,
	0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x19, 0x2e, 0x6e, 0x76, 0x63, 0x74, 0x2e,
	0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6e, 0x76, 0x63, 0x74, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x5b, 0x0a, 0x18, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x1e, 0x2e, 0x6e, 0x76,
	0x63, 0x74, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6e, 0x76,
	0x63, 0x74, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xdb, 0x01, 0x0a,
	0x06, 0x53, 0x6b, 0x79, 0x77, 0x61, 0x79, 0x12, 0x40, 0x0a, 0x0b, 0x41, 0x75, 0x74, 0x68, 0x47,
	0x65, 0x74, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x17, 0x2e, 0x6e, 0x76, 0x63, 0x74, 0x2e, 0x53, 0x6b,
	0x79, 0x77, 0x61, 0x79, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x6e, 0x76, 0x63, 0x74, 0x2e, 0x53, 0x6b, 0x79, 0x77, 0x61, 0x79, 0x41, 0x75, 0x74,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x12, 0x41, 0x75, 0x74,
	0x68, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12,
	0x17, 0x2e, 0x6e, 0x76, 0x63, 0x74, 0x2e, 0x53, 0x6b, 0x79, 0x77, 0x61, 0x79, 0x41, 0x75, 0x74,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6e, 0x76, 0x63, 0x74, 0x2e,
	0x53, 0x6b, 0x79, 0x77, 0x61, 0x79, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x46, 0x0a, 0x11, 0x41, 0x75, 0x74, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x17, 0x2e, 0x6e, 0x76, 0x63, 0x74, 0x2e, 0x53,
	0x6b, 0x79, 0x77, 0x61, 0x79, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x6e, 0x76, 0x63, 0x74, 0x2e, 0x53, 0x6b, 0x79, 0x77, 0x61, 0x79, 0x41, 0x75,
	0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x20, 0x0a, 0x1c, 0x63, 0x6f,
	0x6d, 0x2e, 0x6e, 0x76, 0x69, 0x64, 0x69, 0x61, 0x2e, 0x6b, 0x61, 0x69, 0x7a, 0x65, 0x6e, 0x2e,
	0x6e, 0x76, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nvct_proto_rawDescOnce sync.Once
	file_nvct_proto_rawDescData = file_nvct_proto_rawDesc
)

func file_nvct_proto_rawDescGZIP() []byte {
	file_nvct_proto_rawDescOnce.Do(func() {
		file_nvct_proto_rawDescData = protoimpl.X.CompressGZIP(file_nvct_proto_rawDescData)
	})
	return file_nvct_proto_rawDescData
}

var file_nvct_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_nvct_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_nvct_proto_goTypes = []any{
	(ExecutionStatus)(0), // 0: nvct.ExecutionStatus
	(ArtifactsResponse_ArtifactResponse_ArtifactKindEnum)(0), // 1: nvct.ArtifactsResponse.ArtifactResponse.ArtifactKindEnum
	(*ConnectRequest)(nil),                                  // 2: nvct.ConnectRequest
	(*ConnectResponse)(nil),                                 // 3: nvct.ConnectResponse
	(*HeartbeatRequest)(nil),                                // 4: nvct.HeartbeatRequest
	(*HeartbeatResponse)(nil),                               // 5: nvct.HeartbeatResponse
	(*StringKV)(nil),                                        // 6: nvct.StringKV
	(*ResultMetadata)(nil),                                  // 7: nvct.ResultMetadata
	(*ErrorDetails)(nil),                                    // 8: nvct.ErrorDetails
	(*ResultMetadataRequest)(nil),                           // 9: nvct.ResultMetadataRequest
	(*ResultMetadataResponse)(nil),                          // 10: nvct.ResultMetadataResponse
	(*ArtifactsRequest)(nil),                                // 11: nvct.ArtifactsRequest
	(*ArtifactsResponse)(nil),                               // 12: nvct.ArtifactsResponse
	(*RefreshTokenRequest)(nil),                             // 13: nvct.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),                            // 14: nvct.RefreshTokenResponse
	(*SecretCredentialsRequest)(nil),                        // 15: nvct.SecretCredentialsRequest
	(*SecretCredentialsResponse)(nil),                       // 16: nvct.SecretCredentialsResponse
	(*SkywayAuthRequest)(nil),                               // 17: nvct.SkywayAuthRequest
	(*SkywayAuthResponse)(nil),                              // 18: nvct.SkywayAuthResponse
	(*ArtifactsResponse_ArtifactResponse)(nil),              // 19: nvct.ArtifactsResponse.ArtifactResponse
	(*ArtifactsResponse_ArtifactResponse_ArtifactFile)(nil), // 20: nvct.ArtifactsResponse.ArtifactResponse.ArtifactFile
	(*SkywayAuthResponse_Instance)(nil),                     // 21: nvct.SkywayAuthResponse.Instance
	(*timestamppb.Timestamp)(nil),                           // 22: google.protobuf.Timestamp
}
var file_nvct_proto_depIdxs = []int32{
	0,  // 0: nvct.HeartbeatRequest.status:type_name -> nvct.ExecutionStatus
	0,  // 1: nvct.ResultMetadataRequest.status:type_name -> nvct.ExecutionStatus
	7,  // 2: nvct.ResultMetadataRequest.metadata:type_name -> nvct.ResultMetadata
	8,  // 3: nvct.ResultMetadataRequest.errorDetails:type_name -> nvct.ErrorDetails
	19, // 4: nvct.ArtifactsResponse.artifacts:type_name -> nvct.ArtifactsResponse.ArtifactResponse
	22, // 5: nvct.SecretCredentialsResponse.expiration:type_name -> google.protobuf.Timestamp
	21, // 6: nvct.SkywayAuthResponse.instances:type_name -> nvct.SkywayAuthResponse.Instance
	1,  // 7: nvct.ArtifactsResponse.ArtifactResponse.kind:type_name -> nvct.ArtifactsResponse.ArtifactResponse.ArtifactKindEnum
	20, // 8: nvct.ArtifactsResponse.ArtifactResponse.files:type_name -> nvct.ArtifactsResponse.ArtifactResponse.ArtifactFile
	2,  // 9: nvct.Worker.Connect:input_type -> nvct.ConnectRequest
	4,  // 10: nvct.Worker.SendHeartbeat:input_type -> nvct.HeartbeatRequest
	9,  // 11: nvct.Worker.SendResultMetadata:input_type -> nvct.ResultMetadataRequest
	11, // 12: nvct.Worker.GetArtifacts:input_type -> nvct.ArtifactsRequest
	13, // 13: nvct.Worker.RefreshToken:input_type -> nvct.RefreshTokenRequest
	15, // 14: nvct.Worker.RequestSecretCredentials:input_type -> nvct.SecretCredentialsRequest
	17, // 15: nvct.Skyway.AuthGetLogs:input_type -> nvct.SkywayAuthRequest
	17, // 16: nvct.Skyway.AuthExecuteCommand:input_type -> nvct.SkywayAuthRequest
	17, // 17: nvct.Skyway.AuthListInstances:input_type -> nvct.SkywayAuthRequest
	3,  // 18: nvct.Worker.Connect:output_type -> nvct.ConnectResponse
	5,  // 19: nvct.Worker.SendHeartbeat:output_type -> nvct.HeartbeatResponse
	10, // 20: nvct.Worker.SendResultMetadata:output_type -> nvct.ResultMetadataResponse
	12, // 21: nvct.Worker.GetArtifacts:output_type -> nvct.ArtifactsResponse
	14, // 22: nvct.Worker.RefreshToken:output_type -> nvct.RefreshTokenResponse
	16, // 23: nvct.Worker.RequestSecretCredentials:output_type -> nvct.SecretCredentialsResponse
	18, // 24: nvct.Skyway.AuthGetLogs:output_type -> nvct.SkywayAuthResponse
	18, // 25: nvct.Skyway.AuthExecuteCommand:output_type -> nvct.SkywayAuthResponse
	18, // 26: nvct.Skyway.AuthListInstances:output_type -> nvct.SkywayAuthResponse
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_nvct_proto_init() }
func file_nvct_proto_init() {
	if File_nvct_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nvct_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ConnectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nvct_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ConnectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nvct_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*HeartbeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nvct_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*HeartbeatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nvct_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*StringKV); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nvct_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ResultMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nvct_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ErrorDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nvct_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ResultMetadataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nvct_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*ResultMetadataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nvct_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*ArtifactsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nvct_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*ArtifactsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nvct_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*RefreshTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nvct_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*RefreshTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nvct_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*SecretCredentialsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nvct_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*SecretCredentialsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nvct_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*SkywayAuthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nvct_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*SkywayAuthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nvct_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*ArtifactsResponse_ArtifactResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nvct_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*ArtifactsResponse_ArtifactResponse_ArtifactFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nvct_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*SkywayAuthResponse_Instance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_nvct_proto_msgTypes[2].OneofWrappers = []any{}
	file_nvct_proto_msgTypes[7].OneofWrappers = []any{
		(*ResultMetadataRequest_Metadata)(nil),
		(*ResultMetadataRequest_ErrorDetails)(nil),
	}
	file_nvct_proto_msgTypes[15].OneofWrappers = []any{}
	file_nvct_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nvct_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_nvct_proto_goTypes,
		DependencyIndexes: file_nvct_proto_depIdxs,
		EnumInfos:         file_nvct_proto_enumTypes,
		MessageInfos:      file_nvct_proto_msgTypes,
	}.Build()
	File_nvct_proto = out.File
	file_nvct_proto_rawDesc = nil
	file_nvct_proto_goTypes = nil
	file_nvct_proto_depIdxs = nil
}
