#!/usr/bin/env bash
set -euo pipefail

stack_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
golden_file="$stack_dir/tests/golden/profile-matrix.txt"
work_dir="$(mktemp -d)"
trap 'rm -rf "$work_dir"' EXIT

update_golden=false
case "${1:-}" in
  "") ;;
  --update-golden) update_golden=true ;;
  *)
    echo "usage: $0 [--update-golden]" >&2
    exit 2
    ;;
esac

fail() {
  echo "profile-defaults: $*" >&2
  exit 1
}

for command in helm helmfile yq; do
  command -v "$command" >/dev/null 2>&1 || fail "$command is required"
done

helmfile_args=(
  --file "$stack_dir/helmfile.d/01-observability.yaml.gotmpl"
  --environment default
  --allow-no-matching-release
)

profile_release_json() {
  local profile="$1"
  shift

  HELMFILE_ENV=local helmfile \
    "${helmfile_args[@]}" \
    --state-values-set "observability.profile=$profile" \
    "$@" \
    list --output json --skip-charts 2>/dev/null
}

profile_releases_csv() {
  local profile="$1"
  shift

  profile_release_json "$profile" "$@" |
    yq -p=json -o=yaml -r '.[].name' |
    sort -u |
    paste -sd, -
}

render_monitors() {
  local profile="$1"
  local output_name="$2"
  shift 2
  local output_dir="$work_dir/$output_name"

  mkdir -p "$output_dir"
  HELMFILE_ENV=local helmfile \
    "${helmfile_args[@]}" \
    --state-values-set "observability.profile=$profile" \
    "$@" \
    --selector name=default-monitors \
    template --output-dir "$output_dir" >/dev/null
}

monitor_targets_csv() {
  local output_dir="$1"
  local file

  {
    while IFS= read -r file; do
      yq -N -r \
        'select(.kind == "ServiceMonitor" or .kind == "PodMonitor") | .kind + "/" + .metadata.name' \
        "$file"
    done < <(find "$output_dir" -type f -name '*.yaml' -print | sort)
  } | sort -u | paste -sd, -
}

write_release_values() {
  local profile="$1"
  local release="$2"
  local output_file="$3"
  shift 3

  HELMFILE_ENV=local HELMFILE_CACHE_HOME="$work_dir/helmfile-cache" helmfile \
    "${helmfile_args[@]}" \
    --state-values-set "observability.profile=$profile" \
    "$@" \
    --selector "name=$release" \
    write-values --output-file-template "$output_file" >/dev/null
}

release_needs_csv() {
  local profile="$1"
  local release="$2"
  shift 2

  HELMFILE_ENV=local helmfile \
    "${helmfile_args[@]}" \
    --state-values-set "observability.profile=$profile" \
    "$@" \
    --selector "name=$release" \
    --chart "$stack_dir/charts/nvcf-otel-collector" \
    build 2>/dev/null |
    yq -r '.releases[]? | select(.name == "'"$release"'") | .needs[]?' |
    sort -u |
    paste -sd, -
}

assert_equal() {
  local actual="$1"
  local expected="$2"
  local description="$3"

  [[ "$actual" == "$expected" ]] ||
    fail "$description: expected '$expected', got '$actual'"
}

assert_yaml_value() {
  local file="$1"
  local expression="$2"
  local expected="$3"
  local description="$4"
  local actual

  actual="$(yq -r "$expression" "$file")"
  assert_equal "$actual" "$expected" "$description"
}

assert_release_needs() {
  local case_name="$1"
  local profile="$2"
  local release="$3"
  local expected="$4"
  shift 4

  if [[ "$expected" == "absent" ]]; then
    return
  fi
  if [[ "$expected" == "none" ]]; then
    expected=""
  fi

  local actual
  actual="$(release_needs_csv "$profile" "$release" "$@")"
  assert_equal "$actual" "$expected" "$case_name $release dependencies"
}

generate_profile_matrix() {
  local output_file="$1"
  local profile releases monitors

  {
    echo "# Generated by \`make generate-test-golden\`. Review changes before committing."
    echo '# profile|sorted release names|sorted rendered monitor resources'
    for profile in disabled control compute all; do
      releases="$(profile_releases_csv "$profile")"
      monitors=""
      if [[ "$profile" != "disabled" ]]; then
        render_monitors "$profile" "matrix-$profile"
        monitors="$(monitor_targets_csv "$work_dir/matrix-$profile")"
      fi
      printf '%s|%s|%s\n' "$profile" "$releases" "$monitors"
    done
  } >"$output_file"
}

actual_matrix="$work_dir/profile-matrix.txt"
generate_profile_matrix "$actual_matrix"

if [[ "$update_golden" == "true" ]]; then
  mkdir -p "$(dirname "$golden_file")"
  cp "$actual_matrix" "$golden_file"
  echo "profile-defaults: updated $golden_file"
  exit 0
fi

[[ -f "$golden_file" ]] || fail "missing golden fixture: $golden_file"
if ! diff -u "$golden_file" "$actual_matrix"; then
  fail "profile release or monitor matrix differs from the golden fixture"
fi

fixture_profiles="$(awk -F'|' '!/^#/ {print $1}' "$golden_file" | paste -sd, -)"
assert_equal "$fixture_profiles" "disabled,control,compute,all" \
  "golden profile rows"

service_monitor_template_count="$(
  find "$stack_dir/charts/nvcf-default-monitors/templates" \
    -maxdepth 1 -type f -name '*servicemonitor*.yaml' |
    wc -l |
    tr -d ' '
)"
assert_equal "$service_monitor_template_count" "1" \
  "default monitors chart ServiceMonitor template count"

pod_monitor_template_count="$(
  find "$stack_dir/charts/nvcf-default-monitors/templates" \
    -maxdepth 1 -type f -name '*podmonitor*.yaml' |
    wc -l |
    tr -d ' '
)"
assert_equal "$pod_monitor_template_count" "1" \
  "default monitors chart PodMonitor template count"

# Assert profile-derived release values with write-values. The disabled profile
# is covered by the empty release set in the golden matrix.
for profile in control compute all; do
  collector_values="$work_dir/$profile-collector-values.yaml"
  monitor_values="$work_dir/$profile-monitor-values.yaml"
  write_release_values "$profile" otel-collector "$collector_values"
  write_release_values "$profile" default-monitors "$monitor_values"

  assert_yaml_value "$collector_values" '.targetAllocator.enabled' true \
    "$profile targetAllocator.enabled"
  assert_yaml_value "$collector_values" '.targetAllocatorRbac.create' true \
    "$profile targetAllocatorRbac.create"
  assert_yaml_value "$collector_values" \
    '.config.exporters.prometheusremotewrite.endpoint' \
    'http://vmsingle.monitoring.svc.cluster.local:8428/api/v1/write' \
    "$profile bundled remote-write endpoint"

  case "$profile" in
    control)
      expected_control=true
      expected_compute=false
      ;;
    compute)
      expected_control=false
      expected_compute=true
      ;;
    all)
      expected_control=true
      expected_compute=true
      ;;
  esac
  assert_yaml_value "$monitor_values" '.controlPlane.enabled' \
    "$expected_control" "$profile control monitor group"
  assert_yaml_value "$monitor_values" '.computePlane.enabled' \
    "$expected_compute" "$profile compute monitor group"
done

# Each row exercises a valid install, existing, or disabled ownership shape.
# Dependency expectations are sorted namespace/release pairs. "absent" means
# the release is not owned by this stack, and "none" means it has no needs.
mode_cases=(
  'default-install|control|default-monitors,opentelemetry-operator,otel-collector,prometheus-operator-crds,victoria-metrics|monitoring/opentelemetry-operator,monitoring/prometheus-operator-crds,monitoring/victoria-metrics|monitoring/prometheus-operator-crds|monitoring/prometheus-operator-crds|-|true|true'
  'crds-existing|control|default-monitors,opentelemetry-operator,otel-collector,victoria-metrics|monitoring/opentelemetry-operator,monitoring/victoria-metrics|none|none|--state-values-set=observability.components.prometheusOperatorCrds.mode=existing|true|true'
  'operator-existing|control|default-monitors,otel-collector,prometheus-operator-crds,victoria-metrics|monitoring/prometheus-operator-crds,monitoring/victoria-metrics|absent|monitoring/prometheus-operator-crds|--state-values-set=observability.components.otelOperator.mode=existing|true|true'
  'collector-existing|control|default-monitors,opentelemetry-operator,prometheus-operator-crds,victoria-metrics|absent|monitoring/prometheus-operator-crds|monitoring/prometheus-operator-crds|--state-values-set=observability.components.collector.mode=existing --state-values-set=observability.components.targetAllocator.mode=existing --state-values-set=observability.components.discoveryRbac.mode=existing|absent|absent'
  'collector-disabled|control|default-monitors,opentelemetry-operator,prometheus-operator-crds,victoria-metrics|absent|monitoring/prometheus-operator-crds|monitoring/prometheus-operator-crds|--state-values-set=observability.components.collector.mode=disabled --state-values-set=observability.components.targetAllocator.mode=disabled --state-values-set=observability.components.discoveryRbac.mode=disabled|absent|absent'
  'target-and-rbac-disabled|control|default-monitors,opentelemetry-operator,otel-collector,prometheus-operator-crds,victoria-metrics|monitoring/opentelemetry-operator,monitoring/prometheus-operator-crds,monitoring/victoria-metrics|monitoring/prometheus-operator-crds|monitoring/prometheus-operator-crds|--state-values-set=observability.components.targetAllocator.mode=disabled --state-values-set=observability.components.discoveryRbac.mode=disabled|false|false'
  'rbac-existing|control|default-monitors,opentelemetry-operator,otel-collector,prometheus-operator-crds,victoria-metrics|monitoring/opentelemetry-operator,monitoring/prometheus-operator-crds,monitoring/victoria-metrics|monitoring/prometheus-operator-crds|monitoring/prometheus-operator-crds|--state-values-set=observability.components.discoveryRbac.mode=existing|true|false'
  'backend-existing|control|default-monitors,opentelemetry-operator,otel-collector,prometheus-operator-crds|monitoring/opentelemetry-operator,monitoring/prometheus-operator-crds|monitoring/prometheus-operator-crds|monitoring/prometheus-operator-crds|--state-values-set=metricsBackend.mode=existing --state-values-set=metricsBackend.type=external --state-values-set-string=metricsBackend.remoteWriteEndpoint=https://metrics.example.com/write --state-values-set-string=metricsBackend.promqlEndpoint=https://metrics.example.com|true|true'
  'backend-disabled|compute|default-monitors,opentelemetry-operator,prometheus-operator-crds|absent|monitoring/prometheus-operator-crds|monitoring/prometheus-operator-crds|--state-values-set=observability.components.collector.mode=disabled --state-values-set=observability.components.targetAllocator.mode=disabled --state-values-set=observability.components.discoveryRbac.mode=disabled --state-values-set=metricsBackend.mode=disabled|absent|absent'
  'operator-disabled|control|default-monitors,prometheus-operator-crds,victoria-metrics|absent|absent|monitoring/prometheus-operator-crds|--state-values-set=observability.components.otelOperator.mode=disabled --state-values-set=observability.components.collector.mode=disabled --state-values-set=observability.components.targetAllocator.mode=disabled --state-values-set=observability.components.discoveryRbac.mode=disabled|absent|absent'
)

for row in "${mode_cases[@]}"; do
  IFS='|' read -r case_name profile expected_releases collector_needs \
    operator_needs monitor_needs arg_string target_allocator_enabled \
    target_allocator_rbac_create <<<"$row"

  case_args=()
  if [[ "$arg_string" != "-" ]]; then
    read -r -a case_args <<<"$arg_string"
  fi

  actual_releases="$(profile_releases_csv "$profile" "${case_args[@]}")"
  assert_equal "$actual_releases" "$expected_releases" \
    "$case_name release set"
  assert_release_needs "$case_name" "$profile" otel-collector \
    "$collector_needs" "${case_args[@]}"
  assert_release_needs "$case_name" "$profile" opentelemetry-operator \
    "$operator_needs" "${case_args[@]}"
  assert_release_needs "$case_name" "$profile" default-monitors \
    "$monitor_needs" "${case_args[@]}"

  if [[ "$target_allocator_enabled" != "absent" ]]; then
    values_file="$work_dir/$case_name-collector-values.yaml"
    write_release_values "$profile" otel-collector "$values_file" \
      "${case_args[@]}"
    assert_yaml_value "$values_file" '.targetAllocator.enabled' \
      "$target_allocator_enabled" "$case_name targetAllocator.enabled"
    assert_yaml_value "$values_file" '.targetAllocatorRbac.create' \
      "$target_allocator_rbac_create" \
      "$case_name targetAllocatorRbac.create"
  fi
done

control_monitors="$(awk -F'|' '$1 == "control" {print $3}' "$golden_file")"
compute_monitors="$(awk -F'|' '$1 == "compute" {print $3}' "$golden_file")"
compute_without_worker="${compute_monitors/,PodMonitor\/nvcf-default-monitors-worker/}"

monitor_override_cases=(
  "control-groups-swapped|control|$compute_monitors|--state-values-set=defaultMonitors.controlPlane.enabled=false --state-values-set=defaultMonitors.computePlane.enabled=true"
  "compute-groups-swapped|compute|$control_monitors|--state-values-set=defaultMonitors.controlPlane.enabled=true --state-values-set=defaultMonitors.computePlane.enabled=false"
  "compute-worker-disabled|compute|$compute_without_worker|--state-values-set=defaultMonitors.computePlane.worker.enabled=false"
)

for row in "${monitor_override_cases[@]}"; do
  IFS='|' read -r case_name profile expected_monitors arg_string <<<"$row"
  read -r -a case_args <<<"$arg_string"
  render_monitors "$profile" "$case_name" "${case_args[@]}"
  actual_monitors="$(monitor_targets_csv "$work_dir/$case_name")"
  assert_equal "$actual_monitors" "$expected_monitors" \
    "$case_name rendered monitors"
done

# Keep the packaged chart defaults aligned with the stack-owned values.
mkdir -p "$work_dir/chart-control" "$work_dir/chart-compute"
helm template default-monitors "$stack_dir/charts/nvcf-default-monitors" \
  --set controlPlane.enabled=true \
  >"$work_dir/chart-control/manifests.yaml"
helm template default-monitors "$stack_dir/charts/nvcf-default-monitors" \
  --set computePlane.enabled=true \
  >"$work_dir/chart-compute/manifests.yaml"
assert_equal "$(monitor_targets_csv "$work_dir/chart-control")" \
  "$control_monitors" "chart control monitor defaults"
assert_equal "$(monitor_targets_csv "$work_dir/chart-compute")" \
  "$compute_monitors" "chart compute monitor defaults"

helm template otel-collector "$stack_dir/charts/nvcf-otel-collector" \
  >"$work_dir/collector-manifests.yaml"
grep -q '^      - secrets$' "$work_dir/collector-manifests.yaml" ||
  fail "Target Allocator RBAC must allow referenced Secret discovery"

# Every supported external authentication mode must pass validation and retain
# the external collector endpoint. Autoscaler-specific auth values are covered
# by the self-managed observability test.
external_backend_args=(
  --state-values-set=metricsBackend.mode=existing
  --state-values-set=metricsBackend.type=external
  --state-values-set-string=metricsBackend.remoteWriteEndpoint=https://metrics.example.com/write
  --state-values-set-string=metricsBackend.promqlEndpoint=https://metrics.example.com
)
auth_cases=(
  'none|-'
  'token|--state-values-set-string=metricsBackend.authentication.authnEndpoint=https://auth.example.com'
  'mtls|--state-values-set-string=metricsBackend.authentication.clientCertificatePath=/tls/client.crt --state-values-set-string=metricsBackend.authentication.clientPrivateKeyPath=/tls/client.key'
)

for row in "${auth_cases[@]}"; do
  IFS='|' read -r auth_mode arg_string <<<"$row"
  auth_args=()
  if [[ "$arg_string" != "-" ]]; then
    read -r -a auth_args <<<"$arg_string"
  fi
  case_args=(
    "${external_backend_args[@]}"
    --state-values-set="metricsBackend.authentication.mode=$auth_mode"
    "${auth_args[@]}"
  )

  expected_releases='default-monitors,opentelemetry-operator,otel-collector,prometheus-operator-crds'
  assert_equal "$(profile_releases_csv control "${case_args[@]}")" \
    "$expected_releases" "external $auth_mode release set"
  values_file="$work_dir/external-$auth_mode-collector-values.yaml"
  write_release_values control otel-collector "$values_file" \
    "${case_args[@]}"
  assert_yaml_value "$values_file" \
    '.config.exporters.prometheusremotewrite.endpoint' \
    'https://metrics.example.com/write' \
    "external $auth_mode remote-write endpoint"
done

# The observability namespace is also the default VictoriaMetrics namespace.
# Verify that the shared default propagates to every release, dependency edge,
# and bundled backend endpoint.
observability_namespace_args=(
  --state-values-set=observability.namespace=telemetry
)
observability_namespace_releases="$work_dir/observability-namespace-releases.json"
profile_release_json all "${observability_namespace_args[@]}" \
  >"$observability_namespace_releases"
actual_namespaces="$(
  yq -p=json -o=yaml -r '.[].namespace' \
    "$observability_namespace_releases" |
    sort -u |
    paste -sd, -
)"
assert_equal "$actual_namespaces" telemetry \
  'custom observability namespace release propagation'
assert_release_needs observability-namespace all otel-collector \
  'telemetry/opentelemetry-operator,telemetry/prometheus-operator-crds,telemetry/victoria-metrics' \
  "${observability_namespace_args[@]}"
assert_release_needs observability-namespace all opentelemetry-operator \
  'telemetry/prometheus-operator-crds' \
  "${observability_namespace_args[@]}"
assert_release_needs observability-namespace all default-monitors \
  'telemetry/prometheus-operator-crds' \
  "${observability_namespace_args[@]}"

observability_namespace_values="$work_dir/observability-namespace-collector-values.yaml"
write_release_values all otel-collector "$observability_namespace_values" \
  "${observability_namespace_args[@]}"
assert_yaml_value "$observability_namespace_values" \
  '.config.exporters.prometheusremotewrite.endpoint' \
  'http://vmsingle.telemetry.svc.cluster.local:8428/api/v1/write' \
  'custom observability namespace remote-write endpoint'

# An explicit VictoriaMetrics namespace must override the shared namespace for
# its release, collector dependency, and derived endpoints.
namespace_args=(
  --state-values-set=observability.namespace=telemetry
  --state-values-set=victoriaMetrics.namespace=metrics-store
)
namespace_releases="$work_dir/custom-namespace-releases.json"
profile_release_json all "${namespace_args[@]}" >"$namespace_releases"
namespace_expectations=(
  'default-monitors|telemetry'
  'opentelemetry-operator|telemetry'
  'otel-collector|telemetry'
  'prometheus-operator-crds|telemetry'
  'victoria-metrics|metrics-store'
)
for row in "${namespace_expectations[@]}"; do
  IFS='|' read -r release expected_namespace <<<"$row"
  actual_namespace="$(
    yq -p=json -o=yaml -r \
      '.[] | select(.name == "'"$release"'") | .namespace' \
      "$namespace_releases"
  )"
  assert_equal "$actual_namespace" "$expected_namespace" \
    "custom namespace for $release"
done

assert_release_needs custom-namespaces all otel-collector \
  'metrics-store/victoria-metrics,telemetry/opentelemetry-operator,telemetry/prometheus-operator-crds' \
  "${namespace_args[@]}"
assert_release_needs custom-namespaces all opentelemetry-operator \
  'telemetry/prometheus-operator-crds' "${namespace_args[@]}"
assert_release_needs custom-namespaces all default-monitors \
  'telemetry/prometheus-operator-crds' "${namespace_args[@]}"

custom_namespace_values="$work_dir/custom-namespace-collector-values.yaml"
write_release_values all otel-collector "$custom_namespace_values" \
  "${namespace_args[@]}"
assert_yaml_value "$custom_namespace_values" \
  '.config.exporters.prometheusremotewrite.endpoint' \
  'http://vmsingle.metrics-store.svc.cluster.local:8428/api/v1/write' \
  'custom VictoriaMetrics namespace remote-write endpoint'

# The table covers every fail branch in 01-observability.yaml.gotmpl. Each
# argument is a single Cobra flag so URLs and paths remain shell-safe.
validation_cases=(
  'invalid-profile|observability.profile must be disabled, control, compute, or all|--state-values-set=observability.profile=invalid'
  'invalid-crd-mode|observability.components.prometheusOperatorCrds.mode must be install, existing, or disabled|--state-values-set=observability.profile=control --state-values-set=observability.components.prometheusOperatorCrds.mode=invalid'
  'invalid-operator-mode|observability.components.otelOperator.mode must be install, existing, or disabled|--state-values-set=observability.profile=control --state-values-set=observability.components.otelOperator.mode=invalid'
  'invalid-collector-mode|observability.components.collector.mode must be install, existing, or disabled|--state-values-set=observability.profile=control --state-values-set=observability.components.collector.mode=invalid'
  'invalid-target-mode|observability.components.targetAllocator.mode must be install, existing, or disabled|--state-values-set=observability.profile=control --state-values-set=observability.components.targetAllocator.mode=invalid'
  'invalid-rbac-mode|observability.components.discoveryRbac.mode must be install, existing, or disabled|--state-values-set=observability.profile=control --state-values-set=observability.components.discoveryRbac.mode=invalid'
  'invalid-backend-mode|metricsBackend.mode must be install, existing, or disabled|--state-values-set=observability.profile=control --state-values-set=metricsBackend.mode=invalid'
  'disabled-crd-owner|observability.components.prometheusOperatorCrds.mode cannot be "existing" when observability.profile=disabled|--state-values-set=observability.profile=disabled --state-values-set=observability.components.prometheusOperatorCrds.mode=existing'
  'disabled-operator-owner|observability.components.otelOperator.mode cannot be "install" when observability.profile=disabled|--state-values-set=observability.profile=disabled --state-values-set=observability.components.otelOperator.mode=install'
  'disabled-collector-owner|observability.components.collector.mode cannot be "existing" when observability.profile=disabled|--state-values-set=observability.profile=disabled --state-values-set=observability.components.collector.mode=existing'
  'disabled-target-owner|observability.components.targetAllocator.mode cannot be "install" when observability.profile=disabled|--state-values-set=observability.profile=disabled --state-values-set=observability.components.targetAllocator.mode=install'
  'disabled-rbac-owner|observability.components.discoveryRbac.mode cannot be "existing" when observability.profile=disabled|--state-values-set=observability.profile=disabled --state-values-set=observability.components.discoveryRbac.mode=existing'
  'disabled-backend-owner|metricsBackend.mode cannot be "install" when observability.profile=disabled|--state-values-set=observability.profile=disabled --state-values-set=metricsBackend.mode=install'
  'collector-without-operator|observability.components.otelOperator.mode cannot be disabled when the collector is installed|--state-values-set=observability.profile=compute --state-values-set=observability.components.otelOperator.mode=disabled'
  'collector-target-without-crds|observability.components.prometheusOperatorCrds.mode cannot be disabled when the collector installs the Target Allocator|--state-values-set=observability.profile=compute --state-values-set=observability.components.prometheusOperatorCrds.mode=disabled'
  'monitors-without-crds|observability.components.prometheusOperatorCrds.mode cannot be disabled for an enabled profile|--state-values-set=observability.profile=compute --state-values-set=observability.components.prometheusOperatorCrds.mode=disabled --state-values-set=observability.components.collector.mode=disabled --state-values-set=observability.components.targetAllocator.mode=disabled --state-values-set=observability.components.discoveryRbac.mode=disabled'
  'collector-without-backend|metricsBackend.mode cannot be disabled when the collector is installed|--state-values-set=observability.profile=compute --state-values-set=metricsBackend.mode=disabled'
  'control-without-backend|metricsBackend.mode cannot be disabled for control or all|--state-values-set=observability.profile=control --state-values-set=observability.components.collector.mode=disabled --state-values-set=observability.components.targetAllocator.mode=disabled --state-values-set=observability.components.discoveryRbac.mode=disabled --state-values-set=metricsBackend.mode=disabled'
  'installed-collector-existing-target|observability.components.targetAllocator.mode=existing requires observability.components.collector.mode=existing|--state-values-set=observability.profile=compute --state-values-set=observability.components.targetAllocator.mode=existing'
  'existing-collector-installed-target|observability.components.targetAllocator.mode=install requires observability.components.collector.mode=install|--state-values-set=observability.profile=compute --state-values-set=observability.components.collector.mode=existing --state-values-set=observability.components.targetAllocator.mode=install'
  'existing-collector-installed-rbac|observability.components.discoveryRbac.mode=install requires observability.components.collector.mode=install|--state-values-set=observability.profile=compute --state-values-set=observability.components.collector.mode=existing --state-values-set=observability.components.targetAllocator.mode=existing --state-values-set=observability.components.discoveryRbac.mode=install'
  'target-without-rbac|observability.components.discoveryRbac.mode cannot be disabled when the Target Allocator is installed|--state-values-set=observability.profile=compute --state-values-set=observability.components.discoveryRbac.mode=disabled'
  'invalid-auth-mode|metricsBackend.authentication.mode must be none, token, or mtls|--state-values-set=observability.profile=compute --state-values-set=metricsBackend.authentication.mode=invalid'
  'bundled-external-type|metricsBackend.type must be victoriaMetrics when metricsBackend.mode=install|--state-values-set=observability.profile=compute --state-values-set=metricsBackend.type=external'
  'bundled-auth|metricsBackend.authentication.mode must be none when metricsBackend.mode=install|--state-values-set=observability.profile=compute --state-values-set=metricsBackend.authentication.mode=token'
  'external-victoria-type|metricsBackend.type must be external when metricsBackend.mode=existing|--state-values-set=observability.profile=compute --state-values-set=metricsBackend.mode=existing'
  'external-missing-remote-write|metricsBackend.remoteWriteEndpoint is required when metricsBackend.mode=existing|--state-values-set=observability.profile=compute --state-values-set=metricsBackend.mode=existing --state-values-set=metricsBackend.type=external'
  'control-external-missing-promql|metricsBackend.promqlEndpoint is required for control and all profiles|--state-values-set=observability.profile=control --state-values-set=metricsBackend.mode=existing --state-values-set=metricsBackend.type=external --state-values-set-string=metricsBackend.remoteWriteEndpoint=https://metrics.example.com/write'
  'token-missing-authn|metricsBackend.authentication.authnEndpoint is required for token authentication|--state-values-set=observability.profile=control --state-values-set=metricsBackend.mode=existing --state-values-set=metricsBackend.type=external --state-values-set-string=metricsBackend.remoteWriteEndpoint=https://metrics.example.com/write --state-values-set-string=metricsBackend.promqlEndpoint=https://metrics.example.com --state-values-set=metricsBackend.authentication.mode=token'
  'mtls-missing-client-files|metricsBackend.authentication.clientCertificatePath and clientPrivateKeyPath are required for mtls authentication|--state-values-set=observability.profile=control --state-values-set=metricsBackend.mode=existing --state-values-set=metricsBackend.type=external --state-values-set-string=metricsBackend.remoteWriteEndpoint=https://metrics.example.com/write --state-values-set-string=metricsBackend.promqlEndpoint=https://metrics.example.com --state-values-set=metricsBackend.authentication.mode=mtls'
)

for row in "${validation_cases[@]}"; do
  IFS='|' read -r case_name expected_error arg_string <<<"$row"
  read -r -a case_args <<<"$arg_string"
  log_file="$work_dir/$case_name.log"

  if HELMFILE_ENV=local helmfile \
    "${helmfile_args[@]}" \
    "${case_args[@]}" \
    list --skip-charts >"$log_file" 2>&1; then
    fail "$case_name was accepted"
  fi
  grep -Fq "$expected_error" "$log_file" || {
    cat "$log_file" >&2
    fail "$case_name did not return the expected error: $expected_error"
  }
done

echo "profile-defaults: all checks passed"
