load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "segment",
    srcs = ["segment.go"],
    importpath = "github.com/NVIDIA/nvcf/src/compute-plane-services/request-trace-uploader/internal/segment",
    visibility = ["//src/compute-plane-services/request-trace-uploader:__subpackages__"],
)

go_test(
    name = "segment_test",
    srcs = ["segment_test.go"],
    embed = [":segment"],
)

alias(
    name = "go_default_library",
    actual = ":segment",
    visibility = ["//src/compute-plane-services/request-trace-uploader:__subpackages__"],
)
