# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

navigation:
  - section: Install
    skip-slug: true
    contents:
      - page: Installation Overview
        path: ../../../docs/self-managed/installation.md
      - page: Helmfile Installation
        path: ../../../docs/self-managed/helmfile-installation.md
      - page: CSP End-to-End Example
        path: ../../../docs/self-managed/csp-end-to-end-example-installation.md

  - section: Configure
    skip-slug: true
    contents:
      - section: Gateway and Networking
        skip-slug: true
        contents:
          - page: Gateway Routing
            path: ../../../docs/self-managed/gateway-routing.md
          - page: gRPC Invocation Enablement
            path: ../../../docs/self-managed/grpc-invocation-enablement.md
          - page: LLS Installation
            path: ../../../docs/self-managed/lls-installation.md
      - section: Function Features
        skip-slug: true
        contents:
          - page: LLM Function Enablement
            path: ../../../docs/self-managed/llm-function-enablement.md
          - page: LLM Request Router Load Balancing
            path: ../../../docs/self-managed/llm-request-router-load-balancing.md
          - page: Function Autoscaling Overview
            path: ../../../docs/self-managed/autoscaling/index.md
          - page: Autoscaling Architecture
            slug: architecture
            path: ../../../docs/self-managed/autoscaling/architecture.md
      - page: Registries
        path: ../../../docs/self-managed/registries.md
      - page: NVCF UI
        path: ../../../docs/self-managed/nvcf-ui.md
      - page: Pod Disruption Budgets
        path: ../../../docs/self-managed/pod-disruption-budgets.md

  - section: Operate
    skip-slug: true
    contents:
      - page: Control Plane Operations
        path: ../../../docs/self-managed/control-plane-operations.md
      - page: Troubleshooting
        path: ../../../docs/self-managed/troubleshooting.md
      - page: Autoscaler Operations
        slug: operations
        path: ../../../docs/self-managed/autoscaling/operations.md
      - page: Key Rotation
        path: ../../../docs/self-managed/runbooks/control-plane-key-rotation-mek.md
      - page: Transport TLS Rotation
        path: ../../../docs/self-managed/runbooks/transport-tls-rotation.md
      - page: Quota Management
        path: ../../../docs/self-managed/runbooks/update-nvcf-account-quota-limits.md

  - section: Reference
    skip-slug: true
    contents:
      - page: Environment File Reference
        path: ../../../docs/self-managed/environment-reference.md
