load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "nvca",
    srcs = ["introspect.go"],
    importpath = "github.com/NVIDIA/nvcf/src/control-plane-services/event-ledger/internal/nvca",
    visibility = ["//:__subpackages__"],
)

alias(
    name = "go_default_library",
    actual = ":nvca",
    visibility = ["//:__subpackages__"],
)

go_test(
    name = "nvca_test",
    srcs = ["introspect_test.go"],
    embed = [":nvca"],
    deps = [
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
