# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

filegroup(
    name = "upgrade_test_migrations",
    testonly = True,
    srcs = [
        "03_init_tables.up.sql",
        "04_add_multi_tenant_schema.up.sql",
    ],
    visibility = ["//src/control-plane-services/api-keys:__pkg__"],
)
