/*
SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
SPDX-License-Identifier: Apache-2.0

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package cmd

import (
	"bytes"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"testing"
	"time"

	"nvcf-cli/internal/apikeys"
	"nvcf-cli/internal/client"
	"nvcf-cli/internal/state"

	"github.com/spf13/viper"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// --- parseExtendedDuration ---------------------------------------------------

func TestParseExtendedDuration(t *testing.T) {
	cases := []struct {
		input   string
		want    time.Duration
		wantErr bool
	}{
		{"24h", 24 * time.Hour, false},
		{"90m", 90 * time.Minute, false},
		{"7d", 7 * 24 * time.Hour, false},
		{"2w", 14 * 24 * time.Hour, false},
		{"1d", 24 * time.Hour, false},
		{"", 0, true},
		{"5x", 0, true},
		{"d", 0, true},
		{"w", 0, true},
	}
	for _, tc := range cases {
		t.Run(tc.input, func(t *testing.T) {
			got, err := parseExtendedDuration(tc.input)
			if tc.wantErr {
				require.Error(t, err)
				return
			}
			require.NoError(t, err)
			assert.Equal(t, tc.want, got)
		})
	}
}

// --- runAPIKeyGenerate flag validation ----------------------------------------

// resetApikeyFlags resets the package-level flag vars to their defaults so
// tests do not bleed into one another.
func resetApikeyFlags(t *testing.T) {
	t.Helper()
	t.Cleanup(func() {
		apikeyFor = ""
		apikeyValidate = false
		apikeyScopes = nil
		apikeyExpiresIn = "24h"
		apikeyDescription = "Generated by nvcf-cli"
	})
}

// fakeAPIKeysServer returns a test server that handles both key generation
// (/v1/keys) and introspection (/v1/introspect). It records which issuer
// services and introspect audiences were used so callers can assert on them.
func fakeAPIKeysServer(t *testing.T) (srv *httptest.Server, issuers *[]string, audiences *[]string) {
	t.Helper()
	var capturedIssuers []string
	var capturedAudiences []string
	srv = httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		body, _ := io.ReadAll(r.Body)
		switch r.URL.Path {
		case "/v1/keys":
			issuer := r.Header.Get("Key-Issuer-Service")
			capturedIssuers = append(capturedIssuers, issuer)
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusCreated)
			_, _ = w.Write([]byte(`{"value":"nvapi-fake-key"}`))
		case "/v1/introspect":
			var payload map[string]string
			_ = json.Unmarshal(body, &payload)
			capturedAudiences = append(capturedAudiences, payload["audience_service_id"])
			w.WriteHeader(http.StatusOK)
		default:
			w.WriteHeader(http.StatusNotFound)
		}
	}))
	t.Cleanup(srv.Close)
	return srv, &capturedIssuers, &capturedAudiences
}

// configureApikeyTest points the API keys config at srv and installs a fake
// token so client.LoadConfig succeeds. Resets viper on cleanup.
func configureApikeyTest(t *testing.T, srvURL string) {
	t.Helper()
	home := t.TempDir()
	t.Setenv("HOME", home)

	viper.Reset()
	viper.Set("token", "test-token")
	viper.Set("base_http_url", "http://localhost:9999")
	viper.Set("base_grpc_url", "localhost:50051")
	t.Cleanup(func() { viper.Reset() })

	t.Setenv("api_keys_service_url", srvURL)
	t.Setenv("API_KEYS_SERVICE_ID", "nvcf-test-service-id")
	t.Setenv("api_keys_nvct_service_id", "nvct-test-service-id")
	t.Setenv("API_KEYS_ISSUER_SERVICE", "nvcf-api")
	t.Setenv("api_keys_nvct_issuer_service", "nvct-api")
}

func TestApikeyGenerate_ScopesRequiresFor(t *testing.T) {
	resetApikeyFlags(t)
	srv, _, _ := fakeAPIKeysServer(t)
	configureApikeyTest(t, srv.URL)

	apikeyFor = ""
	apikeyScopes = []string{"invoke_function"}
	apikeyExpiresIn = "1h"

	err := runAPIKeyGenerate(nil, nil)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "--scopes requires --for")
}

func TestApikeyGenerate_UnknownForValue(t *testing.T) {
	resetApikeyFlags(t)
	srv, _, _ := fakeAPIKeysServer(t)
	configureApikeyTest(t, srv.URL)

	apikeyFor = "bogus"
	apikeyExpiresIn = "1h"

	err := runAPIKeyGenerate(nil, nil)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "bogus")
}

func TestApikeyGenerate_FunctionOnly(t *testing.T) {
	resetApikeyFlags(t)
	srv, issuers, _ := fakeAPIKeysServer(t)
	configureApikeyTest(t, srv.URL)

	apikeyFor = "function"
	apikeyExpiresIn = "1h"

	require.NoError(t, runAPIKeyGenerate(nil, nil))

	require.Len(t, *issuers, 1, "expected exactly one key generation call")
	assert.Equal(t, "nvcf-api", (*issuers)[0], "function key should use NVCF issuer")
}

func TestApikeyGenerate_TaskOnly(t *testing.T) {
	resetApikeyFlags(t)
	srv, issuers, _ := fakeAPIKeysServer(t)
	configureApikeyTest(t, srv.URL)

	apikeyFor = "task"
	apikeyExpiresIn = "1h"

	require.NoError(t, runAPIKeyGenerate(nil, nil))

	require.Len(t, *issuers, 1, "expected exactly one key generation call")
	assert.Equal(t, "nvct-api", (*issuers)[0], "task key should use NVCT issuer")
}

func TestApikeyGenerate_BothKeys(t *testing.T) {
	resetApikeyFlags(t)
	srv, issuers, _ := fakeAPIKeysServer(t)
	configureApikeyTest(t, srv.URL)

	apikeyFor = ""
	apikeyExpiresIn = "1h"

	require.NoError(t, runAPIKeyGenerate(nil, nil))

	require.Len(t, *issuers, 2, "expected two key generation calls (function + task)")
	assert.Contains(t, *issuers, "nvcf-api", "should generate function key via NVCF issuer")
	assert.Contains(t, *issuers, "nvct-api", "should generate task key via NVCT issuer")
}

// --- validateAPIKey / validateNVCTAPIKey audience routing ---------------------

// These tests confirm that the validate functions send the correct
// audience_service_id to /v1/introspect. The original bug was that both paths
// used the NVCF service ID, causing NVCT key validation to always fail.

func TestValidateAPIKey_UsesNVCFAudience(t *testing.T) {
	var capturedAudience string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		body, _ := io.ReadAll(r.Body)
		var payload map[string]string
		_ = json.Unmarshal(body, &payload)
		capturedAudience = payload["audience_service_id"]
		w.WriteHeader(http.StatusOK)
	}))
	defer srv.Close()

	t.Setenv("api_keys_service_url", srv.URL)
	t.Setenv("API_KEYS_SERVICE_ID", "nvcf-test-service-id")

	err := validateAPIKey(&client.Config{Token: "fake-token"}, "nvapi-fake-function-key")
	require.NoError(t, err)
	assert.Equal(t, "nvcf-test-service-id", capturedAudience)
}

func TestValidateNVCTAPIKey_UsesNVCTAudience(t *testing.T) {
	var capturedAudience string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		body, _ := io.ReadAll(r.Body)
		var payload map[string]string
		_ = json.Unmarshal(body, &payload)
		capturedAudience = payload["audience_service_id"]
		w.WriteHeader(http.StatusOK)
	}))
	defer srv.Close()

	t.Setenv("api_keys_service_url", srv.URL)
	t.Setenv("api_keys_nvct_service_id", "nvct-test-service-id")

	err := validateNVCTAPIKey(&client.Config{Token: "fake-token"}, "nvapi-fake-task-key")
	require.NoError(t, err)
	assert.Equal(t, "nvct-test-service-id", capturedAudience)
}

func TestValidateAPIKey_AudienceMismatchReturnsError(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusForbidden)
	}))
	defer srv.Close()

	t.Setenv("api_keys_service_url", srv.URL)

	err := validateAPIKey(&client.Config{Token: "fake-token"}, "nvapi-wrong-audience-key")
	require.Error(t, err)
	assert.Contains(t, err.Error(), "not allowed")
}

func TestValidateNVCTAPIKey_AudienceMismatchReturnsError(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusForbidden)
	}))
	defer srv.Close()

	t.Setenv("api_keys_service_url", srv.URL)

	err := validateNVCTAPIKey(&client.Config{Token: "fake-token"}, "nvapi-wrong-audience-key")
	require.Error(t, err)
	assert.Contains(t, err.Error(), "not allowed")
}

func TestApikeyGenerate_ValidateTaskKeyUsesNVCTAudience(t *testing.T) {
	resetApikeyFlags(t)
	srv, _, audiences := fakeAPIKeysServer(t)
	configureApikeyTest(t, srv.URL)

	apikeyFor = "task"
	apikeyValidate = true
	apikeyExpiresIn = "1h"

	require.NoError(t, runAPIKeyGenerate(nil, nil))

	require.Len(t, *audiences, 1, "expected one introspect call")
	assert.Equal(t, "nvct-test-service-id", (*audiences)[0],
		"task key validation must use NVCT audience, not NVCF")
}

func TestApikeyGenerate_ValidateFunctionKeyUsesNVCFAudience(t *testing.T) {
	resetApikeyFlags(t)
	srv, _, audiences := fakeAPIKeysServer(t)
	configureApikeyTest(t, srv.URL)

	apikeyFor = "function"
	apikeyValidate = true
	apikeyExpiresIn = "1h"

	require.NoError(t, runAPIKeyGenerate(nil, nil))

	require.Len(t, *audiences, 1, "expected one introspect call")
	assert.Equal(t, "nvcf-test-service-id", (*audiences)[0],
		"function key validation must use NVCF audience")
}

func TestApikeyGenerate_ValidateBothKeysUsesCorrectAudiences(t *testing.T) {
	resetApikeyFlags(t)
	srv, _, audiences := fakeAPIKeysServer(t)
	configureApikeyTest(t, srv.URL)

	apikeyFor = ""
	apikeyValidate = true
	apikeyExpiresIn = "1h"

	require.NoError(t, runAPIKeyGenerate(nil, nil))

	require.Len(t, *audiences, 2, "expected two introspect calls (function + task)")
	assert.Contains(t, *audiences, "nvcf-test-service-id", "function key must use NVCF audience")
	assert.Contains(t, *audiences, "nvct-test-service-id", "task key must use NVCT audience")
}

func TestApikeyGenerate_FunctionKeyPersistedWhenTaskKeyFails(t *testing.T) {
	// Generating both keys: the function mint succeeds but the task mint fails.
	// The function key must already be persisted to state so it is not lost.
	resetApikeyFlags(t)

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path == "/v1/keys" {
			// The task key is minted with the NVCT issuer; fail only that one.
			if r.Header.Get("Key-Issuer-Service") == "nvct-api" {
				w.WriteHeader(http.StatusInternalServerError)
				return
			}
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusCreated)
			_, _ = w.Write([]byte(`{"value":"nvapi-fn-key"}`))
			return
		}
		w.WriteHeader(http.StatusNotFound)
	}))
	defer srv.Close()

	configureApikeyTest(t, srv.URL)

	// Re-root state at the temp HOME so the save targets a temp file we can read
	// instead of the developer's real ~/.nvcf-cli.state.
	home := os.Getenv("HOME")
	origStateManager := state.DefaultStateManager
	state.DefaultStateManager = state.NewStateManager()
	t.Cleanup(func() { state.DefaultStateManager = origStateManager })

	apikeyFor = ""
	apikeyExpiresIn = "1h"

	err := runAPIKeyGenerate(nil, nil)
	require.Error(t, err, "operation must fail when the task key cannot be minted")
	assert.Contains(t, err.Error(), "task")

	raw, readErr := os.ReadFile(filepath.Join(home, ".nvcf-cli.state"))
	require.NoError(t, readErr, "state file must exist after the function key is minted")
	var saved struct {
		APIKey     string `json:"apiKey"`
		NVCTAPIKey string `json:"nvctApiKey"`
	}
	require.NoError(t, json.Unmarshal(raw, &saved))
	assert.Equal(t, "nvapi-fn-key", saved.APIKey, "function key must be persisted before the task failure")
	assert.Empty(t, saved.NVCTAPIKey, "task key must not be persisted")
}

func TestApikeyGenerate_ValidateRecordsPerKeyResults(t *testing.T) {
	// function key validation fails (403), task key validation passes (200).
	// Each key in the output must carry its own validated/validationError.
	resetApikeyFlags(t)

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		body, _ := io.ReadAll(r.Body)
		switch r.URL.Path {
		case "/v1/keys":
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusCreated)
			_, _ = w.Write([]byte(`{"value":"nvapi-fake-key"}`))
		case "/v1/introspect":
			var payload map[string]string
			_ = json.Unmarshal(body, &payload)
			if payload["audience_service_id"] == "nvcf-test-service-id" {
				w.WriteHeader(http.StatusForbidden)
			} else {
				w.WriteHeader(http.StatusOK)
			}
		default:
			w.WriteHeader(http.StatusNotFound)
		}
	}))
	defer srv.Close()

	configureApikeyTest(t, srv.URL)
	apikeyFor = ""
	apikeyValidate = true
	apikeyExpiresIn = "1h"

	out := captureGenerateJSON(t)

	keys, ok := out["keys"].([]interface{})
	require.True(t, ok, "output must contain a keys list")
	require.Len(t, keys, 2, "both function and task keys must be present")

	byService := map[string]map[string]interface{}{}
	for _, k := range keys {
		entry := k.(map[string]interface{})
		byService[entry["service"].(string)] = entry
	}

	fn := byService["function"]
	require.NotNil(t, fn, "function key must be present")
	assert.Equal(t, false, fn["validated"], "function key validation must fail")
	assert.NotEmpty(t, fn["validationError"], "failed key must carry a validationError")

	task := byService["task"]
	require.NotNil(t, task, "task key must be present")
	assert.Equal(t, true, task["validated"], "task key validation must pass")
}

func TestApikeyGenerate_OutputIncludesPerKeyScopes(t *testing.T) {
	// Without --scopes, each key reports its service default scopes.
	resetApikeyFlags(t)
	srv, _, _ := fakeAPIKeysServer(t)
	configureApikeyTest(t, srv.URL)

	apikeyFor = ""
	apikeyExpiresIn = "1h"

	out := captureGenerateJSON(t)

	keys, ok := out["keys"].([]interface{})
	require.True(t, ok, "output must contain a keys list")
	require.Len(t, keys, 2)

	byService := map[string][]string{}
	for _, k := range keys {
		entry := k.(map[string]interface{})
		var scopes []string
		for _, s := range entry["scopes"].([]interface{}) {
			scopes = append(scopes, s.(string))
		}
		byService[entry["service"].(string)] = scopes
	}

	assert.Equal(t, apikeys.DefaultScopes(), byService["function"], "function key must report function default scopes")
	assert.Equal(t, apikeys.DefaultNVCTScopes(), byService["task"], "task key must report task default scopes")
}

// captureGenerateJSON runs runAPIKeyGenerate in JSON mode and returns the
// parsed stdout object.
func captureGenerateJSON(t *testing.T) map[string]interface{} {
	t.Helper()
	jsonOutput = true
	t.Cleanup(func() { jsonOutput = false })

	oldStdout := os.Stdout
	r, w, err := os.Pipe()
	require.NoError(t, err)
	os.Stdout = w

	require.NoError(t, runAPIKeyGenerate(nil, nil))

	require.NoError(t, w.Close())
	os.Stdout = oldStdout

	var buf bytes.Buffer
	_, err = io.Copy(&buf, r)
	require.NoError(t, err)

	var out map[string]interface{}
	require.NoError(t, json.Unmarshal(buf.Bytes(), &out))
	return out
}
