# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: llm-routing
description: Standalone LLM routing deployment proof of concept
type: application
version: 0.1.0
dependencies:
  - name: helm-nvcf-llm-api-gateway
    alias: gateway
    version: 0.0.0
    repository: file://../llm-api-gateway/llm-api-gateway
  - name: helm-nvcf-llm-request-router
    alias: router
    version: 0.0.0
    repository: file://../llm-request-router/llm-request-router
