# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{{- $serviceToken := required "credentials.serviceToken is required" .Values.credentials.serviceToken -}}
{{- $clientToken := required "credentials.clientToken is required" .Values.credentials.clientToken -}}
{{- if not .Values.credentials.workers -}}
{{- fail "credentials.workers must contain at least one worker" -}}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stargate-dev-auth.fullname" . }}
  labels:
    {{- include "stargate-dev-auth.labels" . | nindent 4 }}
type: Opaque
immutable: true
stringData:
  config.json: {{ dict "serviceToken" $serviceToken "clientToken" $clientToken "workers" .Values.credentials.workers | toJson | quote }}
  service-token.json: {{ dict "nvcfApiToken" $serviceToken | toJson | quote }}
