# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ include "stargate-dev-auth.fullname" . }}
  labels:
    {{- include "stargate-dev-auth.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "stargate-dev-auth.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
      protocol: TCP
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
